[package]
name = "macroquad_sim"
version = "0.1.0"
edition = "2021"

[lib]

crate-type = ["cdylib", "rlib"]

[[bin]]
name = "macroquad_sim"
path = "src/main.rs"

[[bin]]
name = "mask_test"
path = "src/test/mod.rs"

[[bin]]
name = "sfx_test"
path = "src/test/sfx_test.rs"

[[bin]]
name = "slide_test"
path = "src/test/slide_test.rs"

[[bin]]
name = "player"
path = "src/player/player.rs"


[dependencies]
macroquad = { version = "0.4", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hound = "3"
minimp3 = "0.5"
roxmltree = "0.20"
rustfft = "6"
egui-macroquad = { version = "0.17", default-features = false }
rodio = { version = "0.19", default-features = false, features = ["wav"] }
maisimai = { path = "../maisimai" }
#lnmai-core-ffi = {path = "./lnmai-core-ffi"}
[package.metadata.android]
package_name = "com.mai2chart.macroquad_sim"
android_version = 35
target_sdk_version = 35
min_sdk_version = 23
build_targets = ["aarch64-linux-android"]
assets = "assets/"
activity_attributes = { "android:exported" = "true" }
