//! Slide trail / judgment geometry baked from the MajdataPlay Unity prefabs.
//!
//! `assets/slide.svg` (generated by `tools/extract_slide_prefabs.py`) stores one
//! `<g id="TYPE">` per reference slide prefab: an ordered bar-centre polyline
//! plus the baked `slideok` judgment pose. Coordinates are in the prefab's
//! canonical frame — pad centre at the origin, button 1 canonical, **y up**,
//! rotation CCW positive, unit = the A-ring radius (4.8).
//!
//! At runtime a chart slide is mapped to a type string (`line3`, `circle5`, …),
//! reflected/rotated by its start button exactly like the reference
//! (`SlideDrop`), and only then converted to screen space (y down).

use std::sync::OnceLock;

use macroquad::prelude::{Vec2, vec2};

use super::types::SlideShape;

/// The A-ring radius the prefabs are authored against (`SlideGeo.MainRadius`).
pub const PREFAB_UNIT: f32 = 4.8;

/// Baked `slideok` judgment pose, in the prefab frame.
#[derive(Debug, Clone, Copy)]
pub struct OkPose {
    pub pos: Vec2,
    pub rot: f32,
    /// Natural sprite size in prefab units (`4.1×1.4` for curv, …).
    pub size: Vec2,
}

/// One slide prefab: ordered bar centres + per-bar rotations + judgment pose.
#[derive(Debug, Clone)]
pub struct SlideDef {
    pub name: String,
    pub path: Vec<Vec2>,
    /// Per-point bar rotation (radians, CCW+), parallel to `path`.
    pub rots: Vec<f32>,
    pub ok: Option<OkPose>,
}

/// The parsed `assets/slide.svg`.
#[derive(Debug, Clone, Default)]
pub struct SlideSvgDef {
    slides: Vec<SlideDef>,
}

impl SlideSvgDef {
    pub fn from_svg_str(xml: &str) -> Result<Self, String> {
        let doc =
            roxmltree::Document::parse(xml).map_err(|e| format!("slide.svg XML error: {e}"))?;
        let mut slides = Vec::new();
        for g in doc
            .descendants()
            .filter(|n| n.is_element() && n.tag_name().name() == "g")
        {
            let Some(name) = g.attribute("id") else {
                continue;
            };
            let mut path = Vec::new();
            let mut rots = Vec::new();
            let mut ok = None;
            for child in g.children().filter(|n| n.is_element()) {
                match child.tag_name().name() {
                    "polyline" => {
                        let pts = child.attribute("points").unwrap_or("");
                        path = parse_points(pts);
                        rots = child
                            .attribute("data-rots")
                            .unwrap_or("")
                            .split(',')
                            .filter_map(|s| s.trim().parse::<f32>().ok())
                            .map(f32::to_radians)
                            .collect();
                    }
                    "circle" => {
                        let cx = attr_f32(child, "cx")?;
                        let cy = attr_f32(child, "cy")?;
                        let rot = attr_f32(child, "data-rot").unwrap_or(0.0).to_radians();
                        let size = child
                            .attribute("data-size")
                            .and_then(|s| s.split_once(','))
                            .and_then(|(w, h)| Some(vec2(w.trim().parse().ok()?, h.trim().parse().ok()?)))
                            .unwrap_or(vec2(4.1, 1.4));
                        ok = Some(OkPose {
                            pos: vec2(cx, cy),
                            rot,
                            size,
                        });
                    }
                    _ => {}
                }
            }
            if !path.is_empty() {
                slides.push(SlideDef {
                    name: name.to_string(),
                    path,
                    rots,
                    ok,
                });
            }
        }
        if slides.is_empty() {
            return Err("slide.svg contained no slide groups".to_string());
        }
        Ok(Self { slides })
    }

    pub fn get(&self, name: &str) -> Option<&SlideDef> {
        self.slides.iter().find(|s| s.name == name)
    }

    /// Every loaded type name.
    pub fn iter_names(&self) -> impl Iterator<Item = &str> {
        self.slides.iter().map(|s| s.name.as_str())
    }

    pub fn len(&self) -> usize {
        self.slides.len()
    }

    pub fn is_empty(&self) -> bool {
        self.slides.is_empty()
    }
}

/// The baked slide definitions, parsed once from the bundled asset.
pub fn defs() -> &'static SlideSvgDef {
    static DEFS: OnceLock<SlideSvgDef> = OnceLock::new();
    DEFS.get_or_init(|| {
        SlideSvgDef::from_svg_str(include_str!("../../assets/slide.svg"))
            .expect("bundled assets/slide.svg must parse")
    })
}

/// A chart slide mapped onto a reference prefab.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PrefabKey {
    pub name: String,
    /// The prefab evaluated as its X-mirrored (negative-type) variant.
    pub mirror: bool,
}

fn key(name: String, mirror: bool) -> PrefabKey {
    PrefabKey { name, mirror }
}

/// Relative end (1-based, wrapping), matching the reference
/// `NoteCreateHelper.getRelativeEndPos`.
fn rel_end(start: u8, end: u8) -> u8 {
    (((end as i32 - start as i32).rem_euclid(8)) + 1) as u8
}

/// Reference `NoteCreateHelper.MirrorKeys`.
fn mirror_key(k: u8) -> u8 {
    match k {
        1 => 1,
        2 => 8,
        3 => 7,
        4 => 6,
        5 => 5,
        6 => 4,
        7 => 3,
        8 => 2,
        _ => k,
    }
}

/// Reference `NoteCreateHelper.IsUpperHalf` (buttons 7, 8, 1, 2).
fn is_upper_half(k: u8) -> bool {
    matches!(k, 1 | 2 | 7 | 8)
}

/// Map a chart segment onto a prefab type, mirroring the reference
/// `DetectShapeFromText`. Returns `None` when the geometry is out of the
/// reference's valid range (the caller then falls back to procedural drawing).
///
/// * `start` / `end` — 1-based A-ring buttons.
/// * `turn` — the `V` slide's turn button (ignored for other shapes).
pub fn prefab_key(shape: SlideShape, start: u8, end: u8, turn: u8) -> Option<PrefabKey> {
    if !(1..=8).contains(&start) || !(1..=8).contains(&end) {
        return None;
    }
    let r = rel_end(start, end);
    let k = match shape {
        SlideShape::Line => {
            // "-星星至少隔开一键": the endpoints are 3..=7 apart.
            if (3..=7).contains(&r) {
                key(format!("line{r}"), false)
            } else {
                return None;
            }
        }
        SlideShape::Caret => {
            // `^`
            if r < 5 {
                key(format!("circle{r}"), false)
            } else if r > 5 {
                key(format!("circle{}", mirror_key(r)), true)
            } else {
                return None;
            }
        }
        SlideShape::Right => {
            // `>`: upper-half start is the canonical increasing arc; a
            // lower-half start mirrors (reference `DetectShapeFromText`).
            if is_upper_half(start) {
                key(format!("circle{r}"), false)
            } else {
                key(format!("circle{}", mirror_key(r)), true)
            }
        }
        SlideShape::Left => {
            // `<`: lower-half start is the canonical increasing arc; an
            // upper-half start mirrors.
            if !is_upper_half(start) {
                key(format!("circle{r}"), false)
            } else {
                key(format!("circle{}", mirror_key(r)), true)
            }
        }
        SlideShape::VShape => {
            if r == 5 {
                return None;
            }
            key(format!("v{r}"), false)
        }
        SlideShape::P => key(format!("pq{r}"), false),
        SlideShape::Q => key(format!("pq{}", mirror_key(r)), true),
        SlideShape::PP => key(format!("ppqq{r}"), false),
        SlideShape::QQ => key(format!("ppqq{}", mirror_key(r)), true),
        SlideShape::S => key("s".to_string(), false),
        SlideShape::Z => key("s".to_string(), true),
        SlideShape::BigV => {
            let tr = rel_end(start, turn);
            let er = rel_end(start, end);
            if tr == 7 {
                key(format!("L{er}"), false)
            } else if tr == 3 {
                key(format!("L{}", mirror_key(er)), true)
            } else {
                return None;
            }
        }
        SlideShape::Wifi => key("wifi".to_string(), false),
    };
    Some(k)
}

/// Whether the reference selects the R (`true`) or L (`false`) `slideok` sprite,
/// mirroring `NoteCreateHelper.DetectJustType`. Used for the straight-slide
/// judgment fix-up (the prefab's one baked pose is flipped for one of R/L).
pub fn is_just_right(shape: SlideShape, start: u8, end: u8, turn: u8) -> bool {
    match shape {
        SlideShape::Right => is_upper_half(start),
        SlideShape::Left => !is_upper_half(start),
        SlideShape::Caret => {
            // `^`: R when the raw step difference is < 4 (`DetectJustType`),
            // i.e. relative end < 5.
            rel_end(start, end) < 5
        }
        SlideShape::Wifi => is_upper_half(end),
        // `V` and every straight/`pq`/`ppqq`/`s` shape: R when the end button
        // is on the right half.
        _ => !is_upper_half(end),
    }
}

/// Apply the reference `SlideDrop` transform to a prefab point: mirror across X
/// (negative types), then rotate by the start button. Returns the point in the
/// **Unity** prefab frame (unit still 4.8) so callers can keep doing math there.
fn place_unity(p: Vec2, alpha: f32, mirror: bool) -> Vec2 {
    let mut v = p;
    if mirror {
        v.x = -v.x;
    }
    let (s, c) = alpha.sin_cos();
    vec2(v.x * c - v.y * s, v.x * s + v.y * c)
}

/// Unity-frame rotation applied to a prefab local rotation.
fn place_rot_unity(rot: f32, alpha: f32, mirror: bool) -> f32 {
    let mut v = vec2(rot.cos(), rot.sin());
    if mirror {
        v.x = -v.x;
    }
    let (s, c) = alpha.sin_cos();
    let ry = v.x * s + v.y * c;
    // Direction in the Unity frame after the start rotation.
    let rx = v.x * c - v.y * s;
    ry.atan2(rx)
}

/// Unity → screen heading (macroquad y is down).
fn unity_heading_to_screen(rot: f32) -> f32 {
    (-rot.sin()).atan2(rot.cos())
}

/// A placed prefab: screen-space polyline and per-point screen rotations.
#[derive(Debug, Clone)]
pub struct PlacedSlide {
    pub points: Vec<Vec2>,
    pub rots: Vec<f32>,
}

/// Place a prefab for a slide starting at `start` (1-based button).
///
/// `unit` is the screen length of one prefab unit: `(outer_r + tap_offset) /
/// PREFAB_UNIT`, i.e. the on-screen A-ring radius divided by 4.8.
pub fn place(def: &SlideDef, start: u8, mirror: bool, spawn_cx: Vec2, unit: f32) -> PlacedSlide {
    // Reference `SlideDrop.Init`: mirror uses -45°·start, otherwise -45°·(start-1).
    let alpha = if mirror {
        -45.0 * start as f32
    } else {
        -45.0 * (start as f32 - 1.0)
    }
    .to_radians();
    let points = def
        .path
        .iter()
        .map(|&p| {
            let u = place_unity(p, alpha, mirror);
            spawn_cx + vec2(u.x, -u.y) * unit
        })
        .collect();
    let rots = def
        .rots
        .iter()
        .map(|&r| unity_heading_to_screen(place_rot_unity(r, alpha, mirror)))
        .collect();
    PlacedSlide { points, rots }
}

/// Screen-space `slideok` pose: centre + rotation.
pub struct OkScreen {
    pub pos: Vec2,
    pub rot: f32,
    /// Natural sprite size in prefab units (multiply by `unit` for screen px).
    pub size: Vec2,
}

/// Place a prefab's judgment pose. Applies the reference straight/wifi fix-up
/// (flip 180° and nudge 0.27 units) when the prefab's single baked pose is used
/// for the "wrong" side.
#[allow(clippy::too_many_arguments)]
pub fn ok_screen(
    def: &SlideDef,
    start: u8,
    mirror: bool,
    spawn_cx: Vec2,
    unit: f32,
    fix_up: bool,
) -> Option<OkScreen> {
    let ok = def.ok?;
    let alpha = if mirror {
        -45.0 * start as f32
    } else {
        -45.0 * (start as f32 - 1.0)
    }
    .to_radians();
    let mut pos = ok.pos;
    let mut rot = ok.rot;
    if fix_up {
        // SlideDrop.LoadSkin: rotate 180°, then nudge along local -Y by 0.27.
        rot += std::f32::consts::PI;
        let d = vec2(rot.sin(), -rot.cos());
        pos += d * 0.27;
    }
    let u = place_unity(pos, alpha, mirror);
    Some(OkScreen {
        pos: spawn_cx + vec2(u.x, -u.y) * unit,
        rot: unity_heading_to_screen(place_rot_unity(rot, alpha, mirror)),
        size: ok.size,
    })
}

fn parse_points(s: &str) -> Vec<Vec2> {
    s.split_whitespace()
        .filter_map(|pair| {
            let (x, y) = pair.split_once(',')?;
            Some(vec2(x.trim().parse().ok()?, y.trim().parse().ok()?))
        })
        .collect()
}

fn attr_f32(node: roxmltree::Node, name: &str) -> Result<f32, String> {
    node.attribute(name)
        .and_then(|s| s.trim().parse().ok())
        .ok_or_else(|| format!("slide.svg missing attribute {name}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::app::types::SlideShape;

    #[test]
    fn bundled_svg_has_every_reference_type() {
        let def = defs();
        assert_eq!(def.len(), 42);
        for t in [
            "line3", "line7", "circle1", "circle8", "v1", "v8", "ppqq1", "ppqq8", "pq1", "pq8",
            "s", "L2", "L5", "wifi",
        ] {
            assert!(def.get(t).is_some(), "missing {t}");
        }
    }

    #[test]
    fn line3_prefab_matches_the_asset() {
        let d = defs().get("line3").unwrap();
        // Densified (8 subdivisions per original tile gap): 12 gaps → 97 points.
        assert!(d.path.len() >= 90, "n={}", d.path.len());
        assert!((d.path[0] - vec2(2.0187, 3.9956)).length() < 1e-3);
        let ok = d.ok.expect("line3 ok pose");
        assert!((ok.pos - vec2(3.45, 0.2)).length() < 1e-3);
    }

    #[test]
    fn relative_end_and_mirror_match_reference() {
        assert_eq!(rel_end(1, 3), 3);
        assert_eq!(rel_end(3, 1), 7);
        assert_eq!(rel_end(5, 5), 1);
        assert_eq!(mirror_key(2), 8);
        assert_eq!(mirror_key(5), 5);
    }

    #[test]
    fn derives_prefab_types_like_the_reference() {
        // `3-5` → line3 (relative end 3).
        assert_eq!(
            prefab_key(SlideShape::Line, 3, 5, 0),
            Some(PrefabKey { name: "line3".into(), mirror: false })
        );
        // `1>3` (upper-half start) → circle3, no mirror.
        assert_eq!(
            prefab_key(SlideShape::Right, 1, 3, 0),
            Some(PrefabKey { name: "circle3".into(), mirror: false })
        );
        // `5>7` (lower-half start) mirrors → "-circle7".
        assert_eq!(
            prefab_key(SlideShape::Right, 5, 7, 0),
            Some(PrefabKey { name: "circle7".into(), mirror: true })
        );
        // `4<5` (lower-half start, `<`) is the canonical circle2, no mirror.
        assert_eq!(
            prefab_key(SlideShape::Left, 4, 5, 0),
            Some(PrefabKey { name: "circle2".into(), mirror: false })
        );
        // `1<3` (upper-half start) mirrors → "-circle7".
        assert_eq!(
            prefab_key(SlideShape::Left, 1, 3, 0),
            Some(PrefabKey { name: "circle7".into(), mirror: true })
        );
        // `1s5` / `1z5`.
        assert_eq!(
            prefab_key(SlideShape::S, 1, 5, 0),
            Some(PrefabKey { name: "s".into(), mirror: false })
        );
        assert_eq!(
            prefab_key(SlideShape::Z, 1, 5, 0),
            Some(PrefabKey { name: "s".into(), mirror: true })
        );
    }

    /// Advancing the start button by one rotates the whole prefab by 45°.
    #[test]
    fn placing_rotates_to_the_start_button() {
        let d = defs().get("line3").unwrap();
        let spawn = vec2(0.0, 0.0);
        let unit = 100.0; // A-ring = 4.8 units = 480 px
        let a1 = place(d, 1, false, spawn, unit);
        let a3 = place(d, 3, false, spawn, unit);
        let h1 = a1.points[0].y.atan2(a1.points[0].x);
        let h3 = a3.points[0].y.atan2(a3.points[0].x);
        let delta = (h3 - h1).to_degrees();
        assert!((delta - 90.0).abs() < 1e-3, "delta {delta}");
        // The bar centre sits just inside the A-ring.
        let r = a1.points[0].length() / unit;
        assert!((r - PREFAB_UNIT).abs() < 0.75, "radius {r}");
    }
}
