//! Judgment engine bridge to `lnmai-core`'s Lean FFI runtime.
//!
//! The chart is loaded into a persistent Lean runtime session; each gameplay
//! frame the player feeds a [`TimedInputBatch`] (screen sensor presses at the
//! current song time in µs) and renders the commands returned by the core. The
//! player no longer computes judge windows itself.

use lambda_dx::app::types::zone::PadZone;
use lnmai_core::session::{self, Empty, Loaded, Session};
use lnmai_core::types::{
    AudioCommand, ButtonZone, ChartSpec, GameState, JudgeEvent, JudgeEventKind, RenderCommand,
    RuntimeStepLightResult, SensorArea, TimedInputBatch, TimedInputEvent,
};
use std::collections::{HashMap, HashSet};
use std::time::Instant;

/// Map a pad zone to the screen sensor event family.
///
/// This player frontend models only the inner screen sensor. Even A-ring
/// contacts are sent to lnmai-core as A sensors, never as K buttons.
/// Returns `(click_event, hold_down, hold_up)` for one press/release cycle.
pub fn events_for_zone(
    zone: PadZone,
    tp: i64,
) -> Option<(TimedInputEvent, TimedInputEvent, TimedInputEvent)> {
    sensor_events_for_zone(zone, tp)
}

/// Map any pad zone to its corresponding lnmai sensor area.
pub fn sensor_events_for_zone(
    zone: PadZone,
    tp: i64,
) -> Option<(TimedInputEvent, TimedInputEvent, TimedInputEvent)> {
    let area = match zone.to_id() {
        1 => SensorArea::A1,
        2 => SensorArea::A2,
        3 => SensorArea::A3,
        4 => SensorArea::A4,
        5 => SensorArea::A5,
        6 => SensorArea::A6,
        7 => SensorArea::A7,
        8 => SensorArea::A8,
        9 => SensorArea::B1,
        10 => SensorArea::B2,
        11 => SensorArea::B3,
        12 => SensorArea::B4,
        13 => SensorArea::B5,
        14 => SensorArea::B6,
        15 => SensorArea::B7,
        16 => SensorArea::B8,
        17 => SensorArea::C,
        18 => SensorArea::D1,
        19 => SensorArea::D2,
        20 => SensorArea::D3,
        21 => SensorArea::D4,
        22 => SensorArea::D5,
        23 => SensorArea::D6,
        24 => SensorArea::D7,
        25 => SensorArea::D8,
        26 => SensorArea::E1,
        27 => SensorArea::E2,
        28 => SensorArea::E3,
        29 => SensorArea::E4,
        30 => SensorArea::E5,
        31 => SensorArea::E6,
        32 => SensorArea::E7,
        33 => SensorArea::E8,
        _ => return None,
    };
    Some((
        TimedInputEvent::SensorClick { tp, area },
        TimedInputEvent::SensorHold {
            tp,
            area,
            is_down: true,
        },
        TimedInputEvent::SensorHold {
            tp,
            area,
            is_down: false,
        },
    ))
}

fn press_events_from(
    events: Option<(TimedInputEvent, TimedInputEvent, TimedInputEvent)>,
) -> Vec<TimedInputEvent> {
    let mut result = Vec::with_capacity(2);
    if let Some((click, hold_down, _)) = events {
        result.push(click);
        result.push(hold_down);
    }
    result
}

fn release_events_from(
    events: Option<(TimedInputEvent, TimedInputEvent, TimedInputEvent)>,
) -> Vec<TimedInputEvent> {
    events
        .map(|(_, _, hold_up)| vec![hold_up])
        .unwrap_or_default()
}

/// Build the sensor press generated by one active pad zone.
pub fn press_events_for_zone(zone: PadZone, tp: i64) -> Vec<TimedInputEvent> {
    press_events_from(events_for_zone(zone, tp))
}

/// Build the sensor release generated by one active pad zone.
pub fn release_events_for_zone(zone: PadZone, tp: i64) -> Vec<TimedInputEvent> {
    release_events_from(events_for_zone(zone, tp))
}

/// Convert a button zone back to a [`PadZone`] (for engine judge feedback).
pub fn zone_for_button(btn: ButtonZone) -> PadZone {
    let id = match btn {
        ButtonZone::K1 => 1,
        ButtonZone::K2 => 2,
        ButtonZone::K3 => 3,
        ButtonZone::K4 => 4,
        ButtonZone::K5 => 5,
        ButtonZone::K6 => 6,
        ButtonZone::K7 => 7,
        ButtonZone::K8 => 8,
    };
    PadZone::from(id)
}

/// Convert a sensor area to a pad zone id (1-8 A, 9-16 B, 17 C, 18-25 D, 26-33 E).
pub fn zone_for_sensor(area: SensorArea) -> PadZone {
    let id = match area {
        SensorArea::A1 => 1,
        SensorArea::A2 => 2,
        SensorArea::A3 => 3,
        SensorArea::A4 => 4,
        SensorArea::A5 => 5,
        SensorArea::A6 => 6,
        SensorArea::A7 => 7,
        SensorArea::A8 => 8,
        SensorArea::B1 => 9,
        SensorArea::B2 => 10,
        SensorArea::B3 => 11,
        SensorArea::B4 => 12,
        SensorArea::B5 => 13,
        SensorArea::B6 => 14,
        SensorArea::B7 => 15,
        SensorArea::B8 => 16,
        SensorArea::C => 17,
        SensorArea::D1 => 18,
        SensorArea::D2 => 19,
        SensorArea::D3 => 20,
        SensorArea::D4 => 21,
        SensorArea::D5 => 22,
        SensorArea::D6 => 23,
        SensorArea::D7 => 24,
        SensorArea::D8 => 25,
        SensorArea::E1 => 26,
        SensorArea::E2 => 27,
        SensorArea::E3 => 28,
        SensorArea::E4 => 29,
        SensorArea::E5 => 30,
        SensorArea::E6 => 31,
        SensorArea::E7 => 32,
        SensorArea::E8 => 33,
    };
    PadZone::from(id)
}

/// A loaded lnmai-core (FFI) runtime session.
pub struct JudgeEngine {
    session: Session<Loaded>,
    slide_bindings: HashMap<u64, RuntimeSlideBinding>,
}

#[derive(Debug, Clone, Copy)]
struct RuntimeSlideBinding {
    runtime_slide_index: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SlideProgressUpdate {
    pub runtime_slide_index: usize,
    pub hidden_until_bar: usize,
}

fn ensure_runtime() {
    session::ensure_runtime().expect("lnmai-core runtime must initialize");
}

impl JudgeEngine {
    /// Create a session and load the chart at `level_index` from Simai text.
    pub fn load(simai_text: &str, level_index: u32) -> Result<Self, String> {
        ensure_runtime();
        let empty = Session::<Empty>::create().map_err(|e| e.json)?;
        let (loaded, _envelope) = empty
            .load_chart_text(simai_text, level_index)
            .map_err(|e| e.json)?;
        let slide_bindings = runtime_slide_bindings(&loaded)?;
        Ok(JudgeEngine {
            session: loaded,
            slide_bindings,
        })
    }

    /// Advance the runtime by one frame with the given input events at
    /// `current_secs` (song time in seconds, converted to µs ticks). Returns
    /// the complete light-frame result so the player can render core commands.
    pub fn step(
        &mut self,
        current_secs: f32,
        mut events: Vec<TimedInputEvent>,
    ) -> Result<RuntimeStepLightResult, String> {
        events.sort_by_key(|e| e.tp());
        let batch = TimedInputBatch {
            current_time: (current_secs.max(0.0) * 1e6) as i64,
            events,
        };
        let t_ser = Instant::now();
        let json = serde_json::to_string(&batch).map_err(|e| e.to_string())?;
        let ser_ns = t_ser.elapsed();

        let (envelope, ffi_timings) = self
            .session
            .advance_frame_light_timed(&json)
            .map_err(|e| e.json)?;

        let t_de = Instant::now();
        let result = envelope
            .decode_result::<RuntimeStepLightResult>()
            .map_err(|e| e.to_string())?;
        let de_ns = t_de.elapsed();

        crate::perf::record("engine.serialize", ser_ns);
        crate::perf::record(
            "engine.ffi.mk_string",
            std::time::Duration::from_nanos(ffi_timings.mk_string_ns),
        );
        crate::perf::record(
            "engine.ffi.lean",
            std::time::Duration::from_nanos(ffi_timings.ffi_ns),
        );
        crate::perf::record(
            "engine.ffi.into_string",
            std::time::Duration::from_nanos(ffi_timings.into_string_ns),
        );
        crate::perf::record("engine.deserialize", de_ns);

        Ok(result)
    }

    pub fn runtime_slide_index(&self, note_index: u64) -> Option<usize> {
        self.slide_bindings
            .get(&note_index)
            .map(|binding| binding.runtime_slide_index)
    }

    /// Build lnmai-core's default replay tactic (autoplay events) for the
    /// loaded chart. The events carry the same `tp` microsecond timestamps as
    /// runtime input, so the player can feed them frame by frame.
    pub fn default_tactic(&self) -> Result<Vec<TimedInputEvent>, String> {
        let envelope = self.session.get_lowered_chart_json().map_err(|e| e.json)?;
        let chart: ChartSpec = envelope
            .decode_result()
            .map_err(|e| format!("invalid lowered chart json: {e}"))?;
        lnmai_core::api::default_tactic_from_chart(&chart)
            .map(|tactic| tactic.events)
            .map_err(|e| e.json)
    }

    pub fn slide_progress_updates(&self, commands: &[RenderCommand]) -> Vec<SlideProgressUpdate> {
        let mut by_slide: HashMap<usize, usize> = HashMap::new();
        for command in commands {
            let Some(update) = self.slide_progress_update(command) else {
                continue;
            };
            by_slide
                .entry(update.runtime_slide_index)
                .and_modify(|hidden| *hidden = (*hidden).max(update.hidden_until_bar))
                .or_insert(update.hidden_until_bar);
        }

        let mut updates: Vec<_> = by_slide
            .into_iter()
            .map(
                |(runtime_slide_index, hidden_until_bar)| SlideProgressUpdate {
                    runtime_slide_index,
                    hidden_until_bar,
                },
            )
            .collect();
        updates.sort_by_key(|update| update.runtime_slide_index);
        updates
    }

    fn slide_progress_update(&self, command: &RenderCommand) -> Option<SlideProgressUpdate> {
        let (note_index, hidden_until_bar) = match command {
            RenderCommand::UpdateSlideProgress { .. } => return None,
            RenderCommand::UpdateSlideTrackProgress { .. } => return None,
            RenderCommand::HideAllSlideBars { note_index } => (*note_index, usize::MAX),
            RenderCommand::HideSlideBars {
                note_index,
                end_index,
            } => (*note_index, *end_index as usize),
            RenderCommand::HideSlideTrackBars { .. } => return None,
            RenderCommand::ShowJudgeResult { .. } => return None,
        };
        let binding = self.slide_bindings.get(&note_index)?;
        Some(SlideProgressUpdate {
            runtime_slide_index: binding.runtime_slide_index,
            hidden_until_bar,
        })
    }
}

fn runtime_slide_bindings(
    session: &Session<Loaded>,
) -> Result<HashMap<u64, RuntimeSlideBinding>, String> {
    let envelope = session.get_state_json().map_err(|e| e.json)?;
    let state = envelope
        .decode_result::<GameState>()
        .map_err(|e| format!("invalid engine state json: {e}"))?;
    Ok(state
        .slides
        .iter()
        .enumerate()
        .map(|(runtime_slide_index, slide)| {
            (
                slide.params.note_index,
                RuntimeSlideBinding {
                    runtime_slide_index,
                },
            )
        })
        .collect())
}

trait InputTp {
    fn tp(&self) -> i64;
}
impl InputTp for TimedInputEvent {
    fn tp(&self) -> i64 {
        match self {
            TimedInputEvent::ButtonClick { tp, .. }
            | TimedInputEvent::ButtonHold { tp, .. }
            | TimedInputEvent::SensorClick { tp, .. }
            | TimedInputEvent::SensorHold { tp, .. } => *tp,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{
        JudgeEngine, SlideProgressUpdate, chart_note_head_zone, collect_judge_result_displays,
        collect_slide_judge_results, display_label_for_grade, event_position_zone, judge_result_zone,
        judge_sfx_allowed, press_events_for_zone,
    };
    use lambda_dx::simai_io::{parse_simai_source, simai_file_to_chart_doc};
    use lambda_dx::types::zone::PadZone;
    use lambda_dx::types::{
        BpmChange, ChartDoc, Note, NoteType, Slide, SlidePoint, SlideSegment, SlideShape,
    };
    use lnmai_core::types::{
        JudgeEventKind, JudgeGrade, RenderCommand, SensorArea, TimedInputEvent,
    };
    use serde_json::Value;

    fn sample_outer_ring_slide_chart() -> String {
        sample_slide_chart_text(SlideShape::Line, PadZone::from(5_u8))
    }

    fn sample_tap_chart() -> (ChartDoc, String) {
        let chart = ChartDoc {
            version: "1.0".to_string(),
            title: "tap-probe".to_string(),
            artist: String::new(),
            simai_level: 6,
            bpm: 120.0,
            bpms: vec![BpmChange {
                measure: 1.0,
                bpm: 120.0,
            }],
            audio_offset: 0.0,
            notes: vec![Note {
                id: 1,
                time: 1.0,
                lane: 1,
                note_type: NoteType::Tap,
                ..Default::default()
            }],
            templates: vec![],
            template_instances: vec![],
        };
        let file = lambda_dx::simai_io::chart_doc_to_simai_file(&chart);
        let text = lambda_dx::simai_io::export_simai_file(&file);
        (chart, text)
    }

    fn sample_clockwise_circle5_chart() -> String {
        sample_slide_chart_text(SlideShape::Right, PadZone::from(5_u8))
    }

    fn sample_clockwise_circle4_chart() -> String {
        sample_slide_chart_text(SlideShape::Right, PadZone::from(4_u8))
    }

    fn sample_slide_chart(shape: SlideShape, end_zone: PadZone) -> ChartDoc {
        ChartDoc {
            version: "1.0".to_string(),
            title: "outer-ring-slide-probe".to_string(),
            artist: String::new(),
            simai_level: 6,
            bpm: 120.0,
            bpms: vec![BpmChange {
                measure: 1.0,
                bpm: 120.0,
            }],
            audio_offset: 0.0,
            notes: vec![Note {
                id: 1,
                time: 1.0,
                lane: 1,
                note_type: NoteType::Slide,
                is_star: true,
                slide: vec![Slide {
                    segments: vec![SlideSegment {
                        points: vec![SlidePoint::from(end_zone)],
                        shape,
                    }],
                    slide_duration: 1.0,
                    slide_start_delay: 0.25,
                    slide_is_break: false,
                }],
                ..Default::default()
            }],
            templates: vec![],
            template_instances: vec![],
        }
    }

    fn sample_slide_chart_text(shape: SlideShape, end_zone: PadZone) -> String {
        let chart = sample_slide_chart(shape, end_zone);
        let file = lambda_dx::simai_io::chart_doc_to_simai_file(&chart);
        lambda_dx::simai_io::export_simai_file(&file)
    }

    fn sample_slide_chart_and_text(shape: SlideShape, end_zone: PadZone) -> (ChartDoc, String) {
        let chart = sample_slide_chart(shape, end_zone);
        let file = lambda_dx::simai_io::chart_doc_to_simai_file(&chart);
        let text = lambda_dx::simai_io::export_simai_file(&file);
        (chart, text)
    }

    fn session_state(engine: &JudgeEngine) -> Value {
        let envelope = engine
            .session
            .get_state_json()
            .expect("player engine should expose its current state");
        serde_json::from_str(&envelope.json).expect("player engine state should be valid JSON")
    }

    #[test]
    fn importing_then_loading_the_player_engine_does_not_abort() {
        let source = include_str!("../../tests/fixtures/imported-simai/maidata.txt");
        let file = parse_simai_source(source).expect("fixture must parse");
        let chart = simai_file_to_chart_doc(&file, None).expect("fixture must convert");

        let engine = JudgeEngine::load(file.source_text(), chart.simai_level)
            .expect("player engine must load the imported chart");
        drop(engine);
    }

    #[test]
    fn outer_ring_press_is_sensor_only() {
        let events = press_events_for_zone(PadZone::from(1), 123);

        assert_eq!(events.len(), 2);
        assert!(events.iter().all(|event| !matches!(
            event,
            TimedInputEvent::ButtonClick { .. } | TimedInputEvent::ButtonHold { .. }
        )));
        assert!(events.iter().any(|event| {
            matches!(
                event,
                TimedInputEvent::SensorClick {
                    area: SensorArea::A1,
                    ..
                }
            )
        }));
        assert!(events.iter().any(|event| {
            matches!(
                event,
                TimedInputEvent::SensorHold {
                    area: SensorArea::A1,
                    is_down: true,
                    ..
                }
            )
        }));
    }

    #[test]
    fn outer_ring_release_is_sensor_only() {
        let events = super::release_events_for_zone(PadZone::from(1), 123);

        assert_eq!(events.len(), 1);
        assert!(events.iter().any(|event| {
            matches!(
                event,
                TimedInputEvent::SensorHold {
                    area: SensorArea::A1,
                    is_down: false,
                    ..
                }
            )
        }));
    }

    #[test]
    fn non_outer_sensor_press_is_not_duplicated() {
        assert_eq!(press_events_for_zone(PadZone::from(9), 123).len(), 2);
    }

    #[test]
    fn outer_ring_input_advances_the_core_slide_sensor_queue() {
        let mut engine =
            JudgeEngine::load(&sample_outer_ring_slide_chart(), 6).expect("slide chart loads");

        engine
            .step(0.0, Vec::new())
            .expect("initial core frame should succeed");
        engine
            .step(0.8, press_events_for_zone(PadZone::from(1), 800_000))
            .expect("A-ring press should reach the core");

        let state = session_state(&engine);
        let first_area = &state["result"]["slides"][0]["judgeQueues"][0][0];
        assert_eq!(first_area["targetAreas"][0], "A1");
        assert_eq!(
            first_area["wasOn"], true,
            "the player-style A-ring press must be visible as held sensor input"
        );
    }

    #[test]
    fn slide_judge_render_command_maps_to_runtime_slide_body() {
        let mut engine =
            JudgeEngine::load(&sample_outer_ring_slide_chart(), 6).expect("slide chart loads");

        let result = engine
            .step(5.0, Vec::new())
            .expect("missed slide frame should produce core commands");
        let note_index = result
            .render_commands
            .iter()
            .find_map(|command| match command {
                RenderCommand::ShowJudgeResult {
                    kind: JudgeEventKind::Slide,
                    note_index,
                    ..
                } => Some(*note_index),
                _ => None,
            })
            .expect("slide judge render command");

        assert!(
            engine.runtime_slide_index(note_index).is_some(),
            "slide ShowJudgeResult should identify the slide body note"
        );
    }

    #[test]
    fn missed_tap_judge_result_maps_k_position_to_visible_lane() {
        let (chart, text) = sample_tap_chart();
        let mut engine = JudgeEngine::load(&text, 6).expect("tap chart loads");

        let result = engine
            .step(5.0, Vec::new())
            .expect("missed tap frame should produce core commands");
        let (note_index, kind) = result
            .render_commands
            .iter()
            .find_map(|command| match command {
                RenderCommand::ShowJudgeResult {
                    kind, note_index, ..
                } if *kind == JudgeEventKind::Tap => Some((*note_index, *kind)),
                _ => None,
            })
            .expect("tap judge render command");

        assert_eq!(
            event_position_zone(&result.events, note_index, kind),
            Some(PadZone::from(1)),
            "K-button core result positions should map onto the visible A lane"
        );
        assert_eq!(
            chart_note_head_zone(&chart, note_index),
            Some(PadZone::from(1)),
            "the player should still render the core judge command at the chart lane"
        );
    }

    #[test]
    fn core_grades_are_bucketed_for_display_without_rejudging() {
        assert_eq!(display_label_for_grade(JudgeGrade::Perfect), "Perfect");
        assert_eq!(
            display_label_for_grade(JudgeGrade::FastPerfect2nd),
            "Perfect"
        );
        assert_eq!(display_label_for_grade(JudgeGrade::LateGreat), "Great");
        assert_eq!(display_label_for_grade(JudgeGrade::FastGood), "Good");
        assert_eq!(display_label_for_grade(JudgeGrade::Miss), "Miss");
        assert_eq!(display_label_for_grade(JudgeGrade::TooFast), "Miss");
    }

    #[test]
    fn miss_grades_do_not_play_judge_sfx() {
        assert!(!judge_sfx_allowed(JudgeGrade::Miss));
        assert!(!judge_sfx_allowed(JudgeGrade::TooFast));
        assert!(judge_sfx_allowed(JudgeGrade::Perfect));
        assert!(judge_sfx_allowed(JudgeGrade::LateGreat));
    }

    #[test]
    fn slide_judge_result_renders_at_chart_endpoint() {
        let (chart, text) = sample_slide_chart_and_text(SlideShape::Line, PadZone::from(5_u8));
        let mut engine = JudgeEngine::load(&text, 6).expect("slide chart loads");

        let result = engine
            .step(5.0, Vec::new())
            .expect("missed slide frame should produce core commands");
        let (note_index, kind) = result
            .render_commands
            .iter()
            .find_map(|command| match command {
                RenderCommand::ShowJudgeResult {
                    kind: JudgeEventKind::Slide,
                    note_index,
                    ..
                } => Some((*note_index, JudgeEventKind::Slide)),
                _ => None,
            })
            .expect("slide judge render command");

        assert_eq!(
            judge_result_zone(&chart, Some(&engine), &result.events, note_index, kind),
            Some(PadZone::from(5_u8)),
            "slide feedback should be displayed at the chart slide endpoint, not the head"
        );
    }

    #[test]
    fn slide_event_fallback_displays_core_grade_at_endpoint() {
        let (chart, text) = sample_slide_chart_and_text(SlideShape::Line, PadZone::from(5_u8));
        let mut engine = JudgeEngine::load(&text, 6).expect("slide chart loads");

        let mut result = engine
            .step(5.0, Vec::new())
            .expect("missed slide frame should produce core commands");
        result.render_commands.retain(|command| {
            !matches!(
                command,
                RenderCommand::ShowJudgeResult {
                    kind: JudgeEventKind::Slide,
                    ..
                }
            )
        });

        let displays = collect_judge_result_displays(&chart, Some(&engine), &result);

        assert!(
            displays
                .iter()
                .any(|display| display.zone == PadZone::from(5_u8) && display.label == "Miss"),
            "when core emits a slide event without a render command, the player should still display the core grade at the endpoint"
        );
    }

    #[test]
    fn missed_slide_records_miss_just_effect() {
        let (chart, text) = sample_slide_chart_and_text(SlideShape::Line, PadZone::from(5_u8));
        let mut engine = JudgeEngine::load(&text, 6).expect("slide chart loads");

        let result = engine
            .step(5.0, Vec::new())
            .expect("missed slide frame should produce core commands");
        let results = collect_slide_judge_results(&chart, Some(&engine), &result);

        assert!(
            !results.is_empty(),
            "a missed slide should still record a just effect"
        );
        assert!(
            results
                .iter()
                .all(|slide| slide.grade.is_miss_or_too_fast()),
            "the recorded grade should be the core miss"
        );
    }

    #[test]
    fn default_tactic_is_available_for_a_loaded_chart() {
        let (_chart, text) = sample_slide_chart_and_text(SlideShape::Line, PadZone::from(5_u8));
        let engine = JudgeEngine::load(&text, 6).expect("slide chart loads");

        let events = engine
            .default_tactic()
            .expect("lnmai-core default tactic should build");

        assert!(
            !events.is_empty(),
            "autoplay replay tactic should contain at least one input event"
        );
    }

    #[test]
    fn first_circle_area_uses_core_hide_bar_index_for_circle5() {
        let mut engine =
            JudgeEngine::load(&sample_clockwise_circle5_chart(), 6).expect("slide chart loads");

        let result = engine
            .step(1.00, press_events_for_zone(PadZone::from(1), 1_000_000))
            .expect("first body sensor press should reach the core");
        assert!(
            engine
                .slide_progress_updates(&result.render_commands)
                .is_empty(),
            "pressing the first non-final area should not hide bars until release"
        );

        let result = engine
            .step(
                1.30,
                super::release_events_for_zone(PadZone::from(1), 1_300_000),
            )
            .expect("first body sensor release should reach the core");
        assert!(result.render_commands.iter().any(|command| matches!(
            command,
            RenderCommand::HideSlideBars {
                note_index: 1,
                end_index: 3
            }
        )));
        let updates = engine.slide_progress_updates(&result.render_commands);

        assert_eq!(
            updates,
            vec![SlideProgressUpdate {
                runtime_slide_index: 0,
                hidden_until_bar: 3,
            }],
            "the frontend should preserve lnmai-core's bar index instead of treating it as an area count"
        );
    }

    #[test]
    fn first_circle_area_uses_core_hide_bar_index_for_circle4() {
        let mut engine =
            JudgeEngine::load(&sample_clockwise_circle4_chart(), 6).expect("slide chart loads");

        engine
            .step(1.00, press_events_for_zone(PadZone::from(1), 1_000_000))
            .expect("first body sensor press should reach the core");
        let result = engine
            .step(
                1.30,
                super::release_events_for_zone(PadZone::from(1), 1_300_000),
            )
            .expect("first body sensor release should reach the core");

        assert_eq!(
            engine.slide_progress_updates(&result.render_commands),
            vec![SlideProgressUpdate {
                runtime_slide_index: 0,
                hidden_until_bar: 3,
            }],
            "circle4 should use the same first-area bar cutoff as the reference"
        );
    }
}

/// Advance the engine and apply the resulting core render/audio commands.
pub fn step_judge_engine(app: &mut crate::state::PlayerState) {
    if app.judge_engine.is_none() {
        return;
    }
    let t0 = Instant::now();

    app.prepare_engine_frame_events();
    let now = app.song_time();
    let events = std::mem::take(&mut app.engine_events);
    let result = app.judge_engine.as_mut().unwrap().step(now, events);
    app.finish_engine_frame();
    match result {
        Ok(result) => {
            if let Some(engine) = app.judge_engine.as_ref() {
                let updates = engine.slide_progress_updates(&result.render_commands);
                app.apply_core_slide_progress_updates(&updates);
            }
            handle_engine_result(app, result);
        }
        Err(e) => {
            if !app.status.starts_with("判引擎") {
                app.set_status(format!("engine: {e}"));
            }
        }
    }
    crate::perf::record("engine.total", t0.elapsed());
}

fn handle_engine_result(app: &mut crate::state::PlayerState, result: RuntimeStepLightResult) {
    let displays = collect_judge_result_displays(&app.chart, app.judge_engine.as_ref(), &result);
    for display in displays {
        // Slide feedback text is drawn by the slide judge band instead.
        if !display.is_slide {
            app.push_judgement(display.zone, display.label, display.duration);
        }
    }

    // Record slide judgments so the renderer can show the `just` overlay.
    let slide_results = if let Some(engine) = app.judge_engine.as_ref() {
        collect_slide_judge_results(&app.chart, Some(engine), &result)
    } else {
        Vec::new()
    };
    for slide in slide_results {
        app.record_slide_judge(
            slide.note_id,
            slide.slide_idx,
            crate::state::SlideJustKind::from_grade(slide.grade),
        );
    }

    for command in &result.audio_commands {
        play_audio_command(app, command);
    }
}

#[derive(Debug, Clone, Copy)]
struct SlideJudgeResult {
    note_id: u64,
    slide_idx: usize,
    grade: lnmai_core::types::JudgeGrade,
}

/// Map lnmai-core's runtime slide judgments onto the chart's `(note_id,
/// slide_idx)` keys used by the renderer's per-sub-slide effects.
fn collect_slide_judge_results(
    chart: &lambda_dx::app::types::ChartDoc,
    engine: Option<&JudgeEngine>,
    result: &RuntimeStepLightResult,
) -> Vec<SlideJudgeResult> {
    let mut out = Vec::new();
    let mut seen: HashSet<(u64, usize)> = HashSet::new();
    let mut push = |note_index: u64, grade: lnmai_core::types::JudgeGrade| {
        let Some(engine) = engine else { return };
        let Some(runtime_slide_index) = engine.runtime_slide_index(note_index) else {
            return;
        };
        let Some((note_id, slide_idx)) = chart_slide_key(chart, runtime_slide_index) else {
            return;
        };
        if seen.insert((note_id, slide_idx)) {
            out.push(SlideJudgeResult {
                note_id,
                slide_idx,
                grade,
            });
        }
    };

    for command in &result.render_commands {
        if let RenderCommand::ShowJudgeResult {
            kind: JudgeEventKind::Slide,
            grade,
            note_index,
            ..
        } = command
        {
            push(*note_index, *grade);
        }
    }
    for event in &result.events {
        if event.kind == JudgeEventKind::Slide {
            push(event.note_index, event.grade);
        }
    }
    out
}

#[derive(Debug, Clone, PartialEq)]
struct JudgeResultDisplay {
    zone: PadZone,
    label: &'static str,
    duration: f64,
    /// Slide feedback is rendered by the slide judge band (which draws its own
    /// direction-aligned text), so it is not pushed to the generic overlay.
    is_slide: bool,
}

fn collect_judge_result_displays(
    chart: &lambda_dx::app::types::ChartDoc,
    engine: Option<&JudgeEngine>,
    result: &RuntimeStepLightResult,
) -> Vec<JudgeResultDisplay> {
    let mut displays = Vec::new();
    let mut displayed_slide_results: HashSet<u64> = HashSet::new();
    for command in &result.render_commands {
        if let RenderCommand::ShowJudgeResult {
            kind,
            grade,
            note_index,
            ..
        } = command
        {
            if let Some(display) =
                make_judge_result_display(chart, engine, &result.events, *note_index, *kind, *grade)
            {
                if *kind == JudgeEventKind::Slide {
                    displayed_slide_results.insert(*note_index);
                }
                displays.push(display);
            }
        }
    }

    for event in &result.events {
        if event.kind == JudgeEventKind::Slide
            && !displayed_slide_results.contains(&event.note_index)
        {
            if let Some(display) = make_judge_result_display(
                chart,
                engine,
                &result.events,
                event.note_index,
                event.kind,
                event.grade,
            ) {
                displayed_slide_results.insert(event.note_index);
                displays.push(display);
            }
        }
    }

    displays
}

fn make_judge_result_display(
    chart: &lambda_dx::app::types::ChartDoc,
    engine: Option<&JudgeEngine>,
    events: &[JudgeEvent],
    note_index: u64,
    kind: JudgeEventKind,
    grade: lnmai_core::types::JudgeGrade,
) -> Option<JudgeResultDisplay> {
    let zone = judge_result_zone(chart, engine, events, note_index, kind)?;

    let label = display_label_for_grade(grade);
    let duration = if grade.is_miss_or_too_fast() {
        0.24
    } else {
        0.3
    };
    Some(JudgeResultDisplay {
        zone,
        label,
        duration,
        is_slide: kind == JudgeEventKind::Slide,
    })
}

fn judge_result_zone(
    chart: &lambda_dx::app::types::ChartDoc,
    engine: Option<&JudgeEngine>,
    events: &[JudgeEvent],
    note_index: u64,
    kind: JudgeEventKind,
) -> Option<PadZone> {
    if kind == JudgeEventKind::Slide {
        slide_tail_zone_for_runtime_note(chart, engine, note_index)
            .or_else(|| event_position_zone(events, note_index, kind))
    } else {
        event_position_zone(events, note_index, kind)
            .or_else(|| chart_note_head_zone(chart, note_index))
    }
}

fn display_label_for_grade(grade: lnmai_core::types::JudgeGrade) -> &'static str {
    if grade.is_miss_or_too_fast() {
        "Miss"
    } else if grade.is_good_grade() {
        "Good"
    } else if grade.is_great_grade() {
        "Great"
    } else {
        "Perfect"
    }
}

fn judge_sfx_allowed(grade: lnmai_core::types::JudgeGrade) -> bool {
    !grade.is_miss_or_too_fast()
}

fn event_position_zone(
    events: &[JudgeEvent],
    note_index: u64,
    kind: JudgeEventKind,
) -> Option<PadZone> {
    let ev = events
        .iter()
        .find(|ev| ev.note_index == note_index && ev.kind == kind)?;
    if let Some(button) = ev.position.button {
        Some(zone_for_button(button))
    } else {
        ev.position.sensor.map(zone_for_sensor)
    }
}

fn slide_tail_zone_for_runtime_note(
    chart: &lambda_dx::app::types::ChartDoc,
    engine: Option<&JudgeEngine>,
    note_index: u64,
) -> Option<PadZone> {
    let runtime_slide_index = engine.and_then(|engine| engine.runtime_slide_index(note_index))?;
    chart_slide_tail_zone(chart, runtime_slide_index)
}

fn chart_slide_tail_zone(
    chart: &lambda_dx::app::types::ChartDoc,
    runtime_slide_index: usize,
) -> Option<PadZone> {
    chart_slide_key(chart, runtime_slide_index).and_then(|(note_id, slide_idx)| {
        chart
            .notes
            .iter()
            .find(|note| note.id == note_id)
            .and_then(|note| note.slide.get(slide_idx))
            .and_then(|slide| slide.segments.last())
            .and_then(|segment| segment.points.last())
            .map(|point| point.zone)
    })
}

fn chart_note_head_zone(
    chart: &lambda_dx::app::types::ChartDoc,
    note_index: u64,
) -> Option<PadZone> {
    let note = chart
        .notes
        .iter()
        .find(|note| note.id == note_index)
        .or_else(|| {
            usize::try_from(note_index)
                .ok()
                .and_then(|index| chart.notes.get(index.saturating_sub(1)))
        })?;
    Some(PadZone::from(note.lane))
}

pub fn chart_slide_key(
    chart: &lambda_dx::app::types::ChartDoc,
    runtime_slide_index: usize,
) -> Option<(u64, usize)> {
    use lambda_dx::app::types::NoteType;
    let mut current = 0;
    chart
        .notes
        .iter()
        .filter(|note| matches!(note.note_type, NoteType::Slide))
        .find_map(|note| {
            for slide_idx in 0..note.slide.len() {
                if current == runtime_slide_index {
                    return Some((note.id, slide_idx));
                }
                current += 1;
            }
            None
        })
}

fn play_audio_command(app: &mut crate::state::PlayerState, command: &AudioCommand) {
    if !app.audio_enabled {
        return;
    }

    let sfx = match command {
        AudioCommand::PlayJudgeSfx {
            kind,
            grade,
            is_break,
            ..
        } => {
            if !judge_sfx_allowed(*grade) {
                return;
            }
            match kind {
                JudgeEventKind::Break => app.sfx_break_tap.as_ref(),
                JudgeEventKind::Touch => app.sfx_touch.as_ref(),
                JudgeEventKind::Slide if *is_break => app.sfx_break_slide.as_ref(),
                JudgeEventKind::Slide => app.sfx_slide.as_ref(),
                _ if *is_break => app.sfx_break_tap.as_ref(),
                _ => app.sfx_tap.as_ref(),
            }
        }
        AudioCommand::PlaySlideCue { is_break, .. } => {
            if *is_break {
                app.sfx_slide_break_start.as_ref()
            } else {
                app.sfx_slide.as_ref()
            }
        }
    };
    if let (Some(sfx), Some(player)) = (sfx, &mut app.sfx_player) {
        player.play(sfx, 1.0);
    }
}
