//! Judgment engine bridge to `lnmai-core`'s Lean FFI runtime.
//!
//! The chart is loaded into a persistent Lean runtime session; each gameplay
//! frame the player feeds a [`TimedInputBatch`] (screen sensor presses at the
//! current song time in µs) and renders the commands returned by the core. The
//! player no longer computes judge windows itself.
//!
//! Ported from the `features/pure` player's `engine.rs`, trimmed to the pad
//! preview's needs. The Lean project is discovered by `lnmai-core`'s build
//! script (see `lnmai-core/src/build.rs`): a sibling `../lnmai-core` checkout is
//! used when `LNMAI_CORE_ARTIFACTS` is not set.

use crate::app::types::zone::PadZone;
use crate::app::types::{ChartDoc, NoteType};
use crate::player::state::PadPreviewState;
use crate::core::session::{self, Empty, Loaded, Session};
use crate::core::types::{
    AudioCommand, ButtonZone, ChartSpec, GameState, JudgeEvent, JudgeEventKind, JudgeGrade,
    RenderCommand, RuntimeStepLightResult, SensorArea, TimedInputBatch, TimedInputEvent,
};
use std::collections::{HashMap, HashSet};

/// Map a pad zone to the screen sensor event family.
///
/// This frontend models only the inner screen sensor. Even A-ring contacts are
/// sent to lnmai-core as A sensors, never as K buttons. Returns
/// `(click_event, hold_down, hold_up)` for one press/release cycle.
pub fn events_for_zone(
    zone: PadZone,
    tp: i64,
) -> Option<(TimedInputEvent, TimedInputEvent, TimedInputEvent)> {
    let area = match zone.to_id() {
        1 => SensorArea::A1,
        2 => SensorArea::A2,
        3 => SensorArea::A3,
        4 => SensorArea::A4,
        5 => SensorArea::A5,
        6 => SensorArea::A6,
        7 => SensorArea::A7,
        8 => SensorArea::A8,
        9 => SensorArea::B1,
        10 => SensorArea::B2,
        11 => SensorArea::B3,
        12 => SensorArea::B4,
        13 => SensorArea::B5,
        14 => SensorArea::B6,
        15 => SensorArea::B7,
        16 => SensorArea::B8,
        17 => SensorArea::C,
        18 => SensorArea::D1,
        19 => SensorArea::D2,
        20 => SensorArea::D3,
        21 => SensorArea::D4,
        22 => SensorArea::D5,
        23 => SensorArea::D6,
        24 => SensorArea::D7,
        25 => SensorArea::D8,
        26 => SensorArea::E1,
        27 => SensorArea::E2,
        28 => SensorArea::E3,
        29 => SensorArea::E4,
        30 => SensorArea::E5,
        31 => SensorArea::E6,
        32 => SensorArea::E7,
        33 => SensorArea::E8,
        _ => return None,
    };
    Some((
        TimedInputEvent::SensorClick { tp, area },
        TimedInputEvent::SensorHold {
            tp,
            area,
            is_down: true,
        },
        TimedInputEvent::SensorHold {
            tp,
            area,
            is_down: false,
        },
    ))
}

fn press_events_from(
    events: Option<(TimedInputEvent, TimedInputEvent, TimedInputEvent)>,
) -> Vec<TimedInputEvent> {
    match events {
        Some((click, hold_down, _)) => vec![click, hold_down],
        None => Vec::new(),
    }
}

fn release_events_from(
    events: Option<(TimedInputEvent, TimedInputEvent, TimedInputEvent)>,
) -> Vec<TimedInputEvent> {
    events.map(|(_, _, hold_up)| vec![hold_up]).unwrap_or_default()
}

/// Build the sensor press generated by one active pad zone.
pub fn press_events_for_zone(zone: PadZone, tp: i64) -> Vec<TimedInputEvent> {
    press_events_from(events_for_zone(zone, tp))
}

/// Hold-only press for a slide body moving onto `zone` (no `SensorClick`): a
/// slide's head is a click, but its body areas are holds only — sending an extra
/// click per area makes lnmai-core advance an area too early.
pub fn hold_events_for_zone(zone: PadZone, tp: i64) -> Vec<TimedInputEvent> {
    events_for_zone(zone, tp)
        .map(|(_, hold_down, _)| vec![hold_down])
        .unwrap_or_default()
}

/// Build the sensor release generated by one active pad zone.
pub fn release_events_for_zone(zone: PadZone, tp: i64) -> Vec<TimedInputEvent> {
    release_events_from(events_for_zone(zone, tp))
}

/// Convert a button zone back to a [`PadZone`] (for engine judge feedback).
pub fn zone_for_button(btn: ButtonZone) -> PadZone {
    let id = match btn {
        ButtonZone::K1 => 1,
        ButtonZone::K2 => 2,
        ButtonZone::K3 => 3,
        ButtonZone::K4 => 4,
        ButtonZone::K5 => 5,
        ButtonZone::K6 => 6,
        ButtonZone::K7 => 7,
        ButtonZone::K8 => 8,
    };
    PadZone::from(id)
}

/// Convert a sensor area to a pad zone id (1-8 A, 9-16 B, 17 C, 18-25 D, 26-33 E).
pub fn zone_for_sensor(area: SensorArea) -> PadZone {
    let id = match area {
        SensorArea::A1 => 1,
        SensorArea::A2 => 2,
        SensorArea::A3 => 3,
        SensorArea::A4 => 4,
        SensorArea::A5 => 5,
        SensorArea::A6 => 6,
        SensorArea::A7 => 7,
        SensorArea::A8 => 8,
        SensorArea::B1 => 9,
        SensorArea::B2 => 10,
        SensorArea::B3 => 11,
        SensorArea::B4 => 12,
        SensorArea::B5 => 13,
        SensorArea::B6 => 14,
        SensorArea::B7 => 15,
        SensorArea::B8 => 16,
        SensorArea::C => 17,
        SensorArea::D1 => 18,
        SensorArea::D2 => 19,
        SensorArea::D3 => 20,
        SensorArea::D4 => 21,
        SensorArea::D5 => 22,
        SensorArea::D6 => 23,
        SensorArea::D7 => 24,
        SensorArea::D8 => 25,
        SensorArea::E1 => 26,
        SensorArea::E2 => 27,
        SensorArea::E3 => 28,
        SensorArea::E4 => 29,
        SensorArea::E5 => 30,
        SensorArea::E6 => 31,
        SensorArea::E7 => 32,
        SensorArea::E8 => 33,
    };
    PadZone::from(id)
}

/// A loaded lnmai-core (FFI) runtime session.
pub struct JudgeEngine {
    session: Session<Loaded>,
    slide_bindings: HashMap<u64, usize>,
    /// Core slide head timings (µs), indexed by runtime slide index.
    slide_head_timings: Vec<i64>,
    /// Per runtime slide: `(total_judge_queue_len, track_count,
    /// initial_queue_remaining)`, indexed by runtime slide index.
    slide_totals: Vec<(u64, u64, u64)>,
}

fn ensure_runtime() {
    session::ensure_runtime().expect("lnmai-core runtime must initialize");
}

/// Whether the `MAI2_DEBUG_SLIDE` diagnostic trace is enabled.
pub(crate) fn debug_slide_enabled() -> bool {
    use std::sync::OnceLock;
    static ON: OnceLock<bool> = OnceLock::new();
    *ON.get_or_init(|| std::env::var_os("MAI2_DEBUG_SLIDE").is_some())
}

/// Returns `true` only the first time `key` is seen for `tag` (or after it
/// changes), so diagnostics print on transitions instead of every frame.
pub(crate) fn debug_dedup(tag: impl std::fmt::Display, key: &str) -> bool {
    use std::cell::RefCell;
    use std::collections::HashMap;
    thread_local! {
        static LAST: RefCell<HashMap<String, String>> = RefCell::new(HashMap::new());
    }
    let tag = tag.to_string();
    LAST.with(|last| {
        let mut last = last.borrow_mut();
        if last.get(&tag).map(String::as_str) == Some(key) {
            false
        } else {
            last.insert(tag, key.to_string());
            true
        }
    })
}

impl JudgeEngine {
    /// Create a session and load the chart at `level_index` (`&inote_N`) from
    /// Simai text.
    pub fn load(simai_text: &str, level_index: u32) -> Result<Self, String> {
        ensure_runtime();
        let empty = Session::<Empty>::create().map_err(|e| e.json)?;
        let (loaded, _envelope) = empty
            .load_chart_text(simai_text, level_index)
            .map_err(|e| e.json)?;
        let (slide_bindings, slide_head_timings, slide_totals) = runtime_slide_bindings(&loaded)?;
        Ok(JudgeEngine {
            session: loaded,
            slide_bindings,
            slide_head_timings,
            slide_totals,
        })
    }

    /// `(total_judge_queue_len, track_count, initial_queue_remaining)` for a
    /// runtime slide index.
    pub fn slide_queue_total(&self, runtime_slide_index: usize) -> Option<(u64, u64, u64)> {
        self.slide_totals.get(runtime_slide_index).copied()
    }

    /// Diagnostic (`MAI2_DEBUG_SLIDE`): dump the runtime slide bindings.
    pub fn debug_dump_slide_bindings(&self) {
        for (runtime, meta) in self.slide_totals.iter().enumerate() {
            let note_index = self
                .slide_bindings
                .iter()
                .find(|(_, rt)| **rt == runtime)
                .map(|(note, _)| *note);
            eprintln!(
                "[slide/bindings] rt={runtime} note_index={note_index:?} \
                 total_judge_queue={} track_count={} initial_remaining={}",
                meta.0, meta.1, meta.2
            );
        }
    }

    /// Advance the runtime by one frame with the given input events at
    /// `current_secs` (song time in seconds, converted to µs ticks).
    pub fn step(
        &mut self,
        current_secs: f32,
        mut events: Vec<TimedInputEvent>,
    ) -> Result<RuntimeStepLightResult, String> {
        events.sort_by_key(InputTp::tp);
        if std::env::var_os("MAI2_DEBUG_TOUCHZONE").is_some() && !events.is_empty() {
            eprintln!(
                "[touchzone/core] current_time={} events={events:?}",
                (current_secs.max(0.0) * 1e6) as i64
            );
        }
        let batch = TimedInputBatch {
            current_time: (current_secs.max(0.0) * 1e6) as i64,
            events,
        };
        let json = serde_json::to_string(&batch).map_err(|e| e.to_string())?;
        let (envelope, _timings) = self
            .session
            .advance_frame_light_timed(&json)
            .map_err(|e| e.json)?;
        envelope
            .decode_result::<RuntimeStepLightResult>()
            .map_err(|e| e.to_string())
    }

    pub fn runtime_slide_index(&self, note_index: u64) -> Option<usize> {
        self.slide_bindings.get(&note_index).copied()
    }

    /// Number of slides in the loaded runtime chart.
    pub fn slide_count(&self) -> usize {
        self.slide_bindings.len()
    }

    /// Core slide head timing (µs) at `runtime_slide_index`.
    pub fn slide_head_timing(&self, runtime_slide_index: usize) -> Option<i64> {
        self.slide_head_timings.get(runtime_slide_index).copied()
    }

    /// Build lnmai-core's default replay tactic (autoplay events) for the
    /// loaded chart. The events carry microsecond timestamps matching runtime
    /// input, so the player can feed them frame by frame.
    /// The lowered chart (per runtime slide arc: timings + ordered sensor-area
    /// queues with arrow progress). Used to drive a custom autoplay tactic.
    pub fn chart_spec(&self) -> Result<ChartSpec, String> {
        let envelope = self.session.get_lowered_chart_json().map_err(|e| e.json)?;
        envelope
            .decode_result()
            .map_err(|e| format!("invalid lowered chart json: {e}"))
    }

    pub fn default_tactic(&self) -> Result<Vec<TimedInputEvent>, String> {
        let envelope = self.session.get_lowered_chart_json().map_err(|e| e.json)?;
        let chart: ChartSpec = envelope
            .decode_result()
            .map_err(|e| format!("invalid lowered chart json: {e}"))?;
        crate::core::api::default_tactic_from_chart(&chart)
            .map(|tactic| tactic.events)
            .map_err(|e| e.json)
    }

    /// Consumed fraction (0..1) of each runtime slide arc, from a frame's render
    /// commands.
    ///
    /// lnmai reports slide progress per **runtime arc** (one `noteIndex` per arc
    /// of a continuous chain), in its own judge-queue units. The caller slots
    /// each arc's fraction into that arc's segment range of the chart sub-slide,
    /// so a later arc can never be hidden by an earlier arc's progress.
    pub fn slide_progress_updates(&self, commands: &[RenderCommand]) -> Vec<SlideArcProgress> {
        // Keyed by `(runtime arc, track)`: wifi's three tracks report progress
        // independently and must not be merged into one cutoff.
        let mut by_arc: HashMap<(usize, Option<u64>), SlideArcProgress> = HashMap::new();
        for command in commands {
            let Some(update) = self.slide_progress_update(command) else {
                continue;
            };
            let entry = by_arc
                .entry((update.runtime_slide_index, update.track_index))
                .or_insert(SlideArcProgress {
                    runtime_slide_index: update.runtime_slide_index,
                    track_index: update.track_index,
                    frac: 0.0,
                    hidden_until_bar: None,
                });
            entry.frac = entry.frac.max(update.frac);
            entry.hidden_until_bar = match (entry.hidden_until_bar, update.hidden_until_bar) {
                (Some(a), Some(b)) => Some(a.max(b)),
                (a, b) => a.or(b),
            };
        }

        let mut updates: Vec<_> = by_arc.into_values().collect();
        updates.sort_by_key(|update| (update.runtime_slide_index, update.track_index));
        updates
    }

    fn slide_progress_update(&self, command: &RenderCommand) -> Option<SlideArcProgress> {
        let (note_index, track_index, frac, hidden_until_bar) = match command {
            // Per-arc judge progress is the authoritative signal: `remaining`
            // counts down the arc's own judge queue (0 ⇒ arc finished).
            RenderCommand::UpdateSlideProgress {
                note_index,
                remaining,
            } => (
                *note_index,
                None,
                self.frac_from_remaining(*note_index, *remaining)?,
                None,
            ),
            // Wifi reports one of these per track; keep the track identity. Its
            // `remaining` is in per-track units, so it is only a fallback — the
            // authoritative cutoff is `HideSlideTrackBars` below.
            RenderCommand::UpdateSlideTrackProgress {
                note_index,
                track_index,
                remaining,
            } => (
                *note_index,
                Some(*track_index),
                self.frac_from_remaining(*note_index, *remaining)?,
                None,
            ),
            // A miss hides the whole arc.
            RenderCommand::HideAllSlideBars { note_index } => (*note_index, None, 1.0, None),
            // `HideSlideBars`/`HideSlideTrackBars.endIndex` is in trail-tile
            // units (0..sprite count), which is exactly what the renderer hides.
            RenderCommand::HideSlideBars { .. } => return None,
            RenderCommand::HideSlideTrackBars {
                note_index,
                track_index,
                end_index,
            } => (
                *note_index,
                Some(*track_index),
                0.0,
                Some(*end_index as usize),
            ),
            RenderCommand::ShowJudgeResult { .. } => return None,
        };
        let runtime_slide_index = self.runtime_slide_index(note_index)?;
        Some(SlideArcProgress {
            runtime_slide_index,
            track_index,
            frac: frac.clamp(0.0, 1.0),
            hidden_until_bar,
        })
    }

    fn frac_from_remaining(&self, note_index: u64, remaining: u64) -> Option<f32> {
        let runtime = self.runtime_slide_index(note_index)?;
        let (total, _tracks, initial) = self.slide_queue_total(runtime)?;
        // Each runtime arc has its own queue (`initial_queue_remaining`); using
        // the whole-chain `total_judge_queue_len` makes an arc's first update
        // jump several steps. Normalise against the arc's own queue.
        let denom = if initial > 0 { initial } else { total };
        if denom == 0 {
            return None;
        }
        let touched = denom.saturating_sub(remaining).min(denom);
        Some(touched as f32 / denom as f32)
    }
}

/// Consumed fraction (0..1) of one runtime slide arc.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SlideArcProgress {
    pub runtime_slide_index: usize,
    /// Wifi track this progress belongs to, if the core reported a per-track
    /// update (`UpdateSlideTrackProgress` / `HideSlideTrackBars`).
    pub track_index: Option<u64>,
    /// Consumed fraction from the `*Progress` commands (0..1).
    pub frac: f32,
    /// Explicit trail-bar cutoff from `HideSlideTrackBars` (0..sprite count).
    pub hidden_until_bar: Option<usize>,
}

fn runtime_slide_bindings(
    session: &Session<Loaded>,
) -> Result<(HashMap<u64, usize>, Vec<i64>, Vec<(u64, u64, u64)>), String> {
    let envelope = session.get_state_json().map_err(|e| e.json)?;
    let state = envelope
        .decode_result::<GameState>()
        .map_err(|e| format!("invalid engine state json: {e}"))?;
    let index_by_note = state
        .slides
        .iter()
        .enumerate()
        .map(|(runtime_slide_index, slide)| {
            (slide.params.note_index, runtime_slide_index)
        })
        .collect();
    let head_timings = state.slides.iter().map(|slide| slide.head_timing).collect();
    let totals = state
        .slides
        .iter()
        .map(|slide| {
            (
                slide.total_judge_queue_len,
                slide.track_count,
                slide.initial_queue_remaining,
            )
        })
        .collect();
    Ok((index_by_note, head_timings, totals))
}

trait InputTp {
    fn tp(&self) -> i64;
}
impl InputTp for TimedInputEvent {
    fn tp(&self) -> i64 {
        match self {
            TimedInputEvent::ButtonClick { tp, .. }
            | TimedInputEvent::ButtonHold { tp, .. }
            | TimedInputEvent::SensorClick { tp, .. }
            | TimedInputEvent::SensorHold { tp, .. } => *tp,
        }
    }
}

/// Microsecond timestamp of a core input event.
pub fn timed_input_tp(event: &TimedInputEvent) -> i64 {
    event.tp()
}

/// Adapt lnmai-core's outer-button autoplay events to this player's sensor-only
/// input surface. The pad has no K buttons, so K1..K8 are represented by the
/// corresponding A1..A8 sensor events before the frame is sent back to core.
pub fn normalize_tactic_event(event: TimedInputEvent) -> TimedInputEvent {
    match event {
        TimedInputEvent::ButtonClick { tp, zone } => TimedInputEvent::SensorClick {
            tp,
            area: sensor_area_for_button(zone),
        },
        TimedInputEvent::ButtonHold {
            tp,
            zone,
            is_down,
        } => TimedInputEvent::SensorHold {
            tp,
            area: sensor_area_for_button(zone),
            is_down,
        },
        sensor_event => sensor_event,
    }
}

fn sensor_area_for_button(zone: ButtonZone) -> SensorArea {
    match zone {
        ButtonZone::K1 => SensorArea::A1,
        ButtonZone::K2 => SensorArea::A2,
        ButtonZone::K3 => SensorArea::A3,
        ButtonZone::K4 => SensorArea::A4,
        ButtonZone::K5 => SensorArea::A5,
        ButtonZone::K6 => SensorArea::A6,
        ButtonZone::K7 => SensorArea::A7,
        ButtonZone::K8 => SensorArea::A8,
    }
}

/// Advance the engine and apply the resulting core judge/audio commands.
///
/// Normally the frame's inputs are handed to the core in one batch at the frame
/// clock. But a very fast slide (e.g. a long `^` chain at `[8:1]`) packs several
/// arc transitions into a single ~16 ms frame; under one shared clock the core
/// expires the earlier arc before its input is applied (Miss). When a frame's
/// events span more than a few milliseconds they are therefore stepped one at a
/// time at their own timestamps, which keeps the clock aligned with each arc.
///
/// Diagnostic overrides: `MAI2_DEBUG_FORCE_BATCH` treats every frame as normal
/// (batched), `MAI2_DEBUG_FORCE_PEREVENT` steps every frame per event.
/// Play the 击打音 for a hold / touch-hold **head** the instant it is pressed.
///
/// The core reports a hold only at its tail (`stepRegularHoldHead*` emits no
/// event), so the head hit is detected locally from the input events: a press
/// on the hold's lane within its head window plays the note's hit sound (tap
/// for a regular hold, touch for a touch-hold) exactly once.
fn play_hold_head_hits(app: &mut PadPreviewState, events: &[TimedInputEvent]) {
    use crate::player::render::skin::SkinVariant;
    use crate::player::sfx::{self, SfxKind};

    const HEAD_WINDOW_SEC: f32 = 0.10;
    let mut hits: Vec<(u64, SfxKind, bool)> = Vec::new();
    for event in events {
        let (tp, zone, down) = match event {
            TimedInputEvent::SensorClick { tp, area } => (*tp, zone_for_sensor(*area), true),
            TimedInputEvent::SensorHold { tp, area, is_down } => {
                (*tp, zone_for_sensor(*area), *is_down)
            }
            TimedInputEvent::ButtonClick { tp, zone } => (*tp, zone_for_button(*zone), true),
            TimedInputEvent::ButtonHold { tp, zone, is_down } => {
                (*tp, zone_for_button(*zone), *is_down)
            }
        };
        if !down {
            continue;
        }
        let t = tp as f32 / 1e6;
        for note in &app.chart.notes {
            if !matches!(note.note_type, NoteType::Hold | NoteType::TouchHold) {
                continue;
            }
            if note.lane != zone.to_id() || app.hold_head_hits.contains(&note.id) {
                continue;
            }
            if hits.iter().any(|(id, ..)| *id == note.id) {
                continue;
            }
            let ns = crate::app::types::note_secs(note, &app.chart.bpms);
            if (t - ns).abs() > HEAD_WINDOW_SEC {
                continue;
            }
            let kind = if note.is_touch {
                SfxKind::Touch
            } else {
                SfxKind::Tap
            };
            hits.push((note.id, kind, note.is_break));
        }
    }
    for (id, kind, is_break) in hits {
        let buf = sfx::select(app, kind, SkinVariant::of_flags(is_break, false), false);
        app.play_sfx(buf);
        app.hold_head_hits.insert(id);
    }
}

pub fn step_judge_engine(app: &mut PadPreviewState) {
    // `no_core`: bypass lnmai-core entirely (pre-lnmai autoplay + star motion).
    if !app.use_core() {
        return;
    }
    let now = app.song_time();
    let events = std::mem::take(&mut app.engine_events);
    // The core reports a hold only at its tail, so play the **head** hit here
    // the moment it is actually pressed (a regular hold uses tap.wav, a
    // touch-hold touch.wav).
    play_hold_head_hits(app, &events);
    let results = {
        let engine = app.judge_engine.as_mut().unwrap();
        step_engine_events(engine, now, events)
    };
    for result in results {
        match result {
            Ok(result) => {
                app.core_score = Some(result.score.clone());
                if let Some(engine) = app.judge_engine.as_ref() {
                    if debug_slide_enabled() {
                        log_lnmai_slide_state(engine, now, &result);
                    }
                    let updates = engine.slide_progress_updates(&result.render_commands);
                    app.apply_core_slide_progress_updates(&updates);
                }
                handle_engine_result(app, result);
            }
            Err(e) => {
                if !app.status.starts_with("engine") {
                    app.set_status(format!("engine: {e}"));
                }
            }
        }
    }
}

/// Events in one frame that span at most this many microseconds are treated as
/// one batch ("normal frame"). Beyond it the frame contains a sub-frame slide
/// arc and is stepped per event. See [`step_judge_engine`].
const FRAME_INPUT_BATCH_SPAN_US: i64 = 5_000;

/// `MAI2_DEBUG_FORCE_BATCH`: force **every** frame to be treated as a normal
/// (batched) frame, even ones holding a sub-frame arc.
fn force_batch() -> bool {
    use std::sync::OnceLock;
    static ON: OnceLock<bool> = OnceLock::new();
    *ON.get_or_init(|| std::env::var_os("MAI2_DEBUG_FORCE_BATCH").is_some())
}

/// `MAI2_DEBUG_FORCE_PEREVENT`: force **every** frame to be stepped per event,
/// even ordinary ones.
fn force_per_event() -> bool {
    use std::sync::OnceLock;
    static ON: OnceLock<bool> = OnceLock::new();
    *ON.get_or_init(|| std::env::var_os("MAI2_DEBUG_FORCE_PEREVENT").is_some())
}

pub(crate) fn step_engine_events(
    engine: &mut JudgeEngine,
    now: f32,
    mut events: Vec<TimedInputEvent>,
) -> Vec<Result<RuntimeStepLightResult, String>> {
    if events.is_empty() {
        return vec![engine.step(now, Vec::new())];
    }
    events.sort_by_key(timed_input_tp);
    let per_event = if force_per_event() {
        true
    } else if force_batch() {
        false
    } else {
        let span = timed_input_tp(events.last().unwrap()) - timed_input_tp(&events[0]);
        span > FRAME_INPUT_BATCH_SPAN_US
    };
    if !per_event {
        return vec![engine.step(now, events)];
    }
    let mut results = Vec::with_capacity(events.len() + 1);
    for event in events {
        let at = (timed_input_tp(&event) as f32 / 1e6).min(now.max(0.0));
        results.push(engine.step(at, vec![event]));
    }
    results.push(engine.step(now, Vec::new()));
    results
}

/// Diagnostic: dump lnmai-core's slide state — for each runtime arc, its
/// **traveled / total** length (judge-queue units), plus hide commands and slide
/// judge events. Enabled by `MAI2_DEBUG_SLIDE`.
fn log_lnmai_slide_state(engine: &JudgeEngine, now: f32, result: &RuntimeStepLightResult) {
    for command in &result.render_commands {
        let (tag, note_index, line) = match command {
            RenderCommand::UpdateSlideProgress {
                note_index,
                remaining,
            } => {
                let rt = engine.runtime_slide_index(*note_index);
                let total = rt.and_then(|rt| engine.slide_queue_total(rt)).map(|t| t.0);
                let traveled = total.map(|t| t.saturating_sub(*remaining));
                (
                    "progress",
                    *note_index,
                    format!(
                        "star note={note_index} rt={rt:?} traveled={traveled:?}/{total:?} \
                         (remaining={remaining}) UpdateSlideProgress"
                    ),
                )
            }
            RenderCommand::UpdateSlideTrackProgress {
                note_index,
                track_index,
                remaining,
            } => {
                let rt = engine.runtime_slide_index(*note_index);
                let meta = rt.and_then(|rt| engine.slide_queue_total(rt));
                let total = meta.map(|t| t.0);
                let tracks = meta.map(|t| t.1);
                let traveled = total.map(|t| t.saturating_sub(*remaining));
                (
                    "track",
                    *note_index,
                    format!(
                        "star note={note_index} rt={rt:?} traveled={traveled:?}/{total:?} \
                         (remaining={remaining}) UpdateSlideTrackProgress track={track_index}/{tracks:?}"
                    ),
                )
            }
            RenderCommand::HideAllSlideBars { note_index } => {
                let rt = engine.runtime_slide_index(*note_index);
                let total = rt.and_then(|rt| engine.slide_queue_total(rt)).map(|t| t.0);
                (
                    "hideall",
                    *note_index,
                    format!(
                        "star note={note_index} rt={rt:?} traveled={total:?}/{total:?} HideAllSlideBars"
                    ),
                )
            }
            RenderCommand::HideSlideBars {
                note_index,
                end_index,
            } => {
                let rt = engine.runtime_slide_index(*note_index);
                let total = rt.and_then(|rt| engine.slide_queue_total(rt)).map(|t| t.0);
                (
                    "hidebars",
                    *note_index,
                    format!(
                        "star note={note_index} rt={rt:?} hide_end_index={end_index}/{total:?} \
                         HideSlideBars (trail-tile units)"
                    ),
                )
            }
            _ => continue,
        };
        if debug_dedup(format!("lnmai/{tag}/{note_index}"), &line) {
            eprintln!("[slide/lnmai t={now:.3}] {line}");
        }
    }
    for event in &result.events {
        if event.kind == JudgeEventKind::Slide {
            let runtime = engine.runtime_slide_index(event.note_index);
            let line = format!(
                "judge note={} rt={runtime:?} grade={:?}",
                event.note_index, event.grade
            );
            let key = format!("lnmai/judge/{}", event.note_index);
            if debug_dedup(key, &line) {
                eprintln!("[slide/lnmai t={now:.3}] {line}");
            }
        }
    }
}

fn handle_engine_result(app: &mut PadPreviewState, result: RuntimeStepLightResult) {
    let displays = collect_judge_result_displays(&app.chart, app.judge_engine.as_ref(), &result);
    for display in displays {
        app.push_judgement(display.zone, display.label, display.duration);
        // Tap-family hits and any break note get the ring/spark burst — only on
        // an actual hit (a miss shows the text but no burst).
        if display.is_hit
            && (matches!(display.kind, JudgeEventKind::Tap | JudgeEventKind::Break)
                || display.is_break)
        {
            app.push_hit_fx(display.zone, display.label, display.is_break);
        }
    }
    // Record slide judgments so the renderer can show the `slideok` overlay.
    for fx in collect_slide_judge_fx(&app.chart, app.judge_engine.as_ref(), &result) {
        app.record_slide_judge(fx.note_id, fx.slide_idx, fx.grade);
    }
    // A touch note vanishes the instant it is judged (hit or miss), matching
    // MajdataPlay's `TouchDrop.End`, instead of lingering for a fixed time.
    let judged_touch: Vec<u64> = result
        .events
        .iter()
        .filter(|event| event.kind == JudgeEventKind::Touch)
        .filter_map(|event| chart_note(&app.chart, event.note_index))
        .filter(|note| matches!(note.note_type, NoteType::Touch))
        .map(|note| note.id)
        .collect();
    for id in judged_touch {
        app.hidden_notes.insert(id);
    }
    for command in &result.audio_commands {
        play_audio_command(app, command);
    }
}

/// A slide judgment mapped onto a chart sub-slide, for the `slideok` overlay.
struct SlideJudgeFxResult {
    note_id: u64,
    slide_idx: usize,
    grade: crate::player::state::SlideJudgeGrade,
}

/// Collect lnmai-core's slide judgments and map each runtime note onto the
/// chart's `(note_id, slide_idx)` key used by the renderer's per-sub-slide fx.
fn collect_slide_judge_fx(
    chart: &ChartDoc,
    engine: Option<&JudgeEngine>,
    result: &RuntimeStepLightResult,
) -> Vec<SlideJudgeFxResult> {
    use crate::player::state::SlideJudgeGrade;

    let mut out = Vec::new();
    let mut seen: HashSet<(u64, usize)> = HashSet::new();
    let mut push = |note_index: u64, grade: JudgeGrade| {
        let Some(engine) = engine else { return };
        let Some(runtime_slide_index) = engine.runtime_slide_index(note_index) else {
            return;
        };
        let Some((note_id, slide_idx)) = chart_slide_key(chart, runtime_slide_index) else {
            return;
        };
        if seen.insert((note_id, slide_idx)) {
            out.push(SlideJudgeFxResult {
                note_id,
                slide_idx,
                grade: SlideJudgeGrade::from_grade(grade),
            });
        }
    };

    for command in &result.render_commands {
        if let RenderCommand::ShowJudgeResult {
            kind: JudgeEventKind::Slide,
            grade,
            note_index,
            ..
        } = command
        {
            push(*note_index, *grade);
        }
    }
    for event in &result.events {
        if event.kind == JudgeEventKind::Slide {
            push(event.note_index, event.grade);
        }
    }
    out
}

#[derive(Debug, Clone, PartialEq)]
struct JudgeResultDisplay {
    zone: PadZone,
    label: &'static str,
    duration: f64,
    kind: JudgeEventKind,
    is_break: bool,
    /// True when the note was actually hit (not a miss / too-fast).
    is_hit: bool,
}

/// Map lnmai-core's render/event results onto (zone, label) feedbacks.
fn collect_judge_result_displays(
    chart: &ChartDoc,
    engine: Option<&JudgeEngine>,
    result: &RuntimeStepLightResult,
) -> Vec<JudgeResultDisplay> {
    let mut displays = Vec::new();
    let mut displayed_slide_results: HashSet<u64> = HashSet::new();
    for command in &result.render_commands {
        if let RenderCommand::ShowJudgeResult {
            kind,
            grade,
            note_index,
            ..
        } = command
        {
            if let Some(display) =
                make_judge_result_display(chart, engine, &result.events, *note_index, *kind, *grade)
            {
                if *kind == JudgeEventKind::Slide {
                    displayed_slide_results.insert(*note_index);
                }
                displays.push(display);
            }
        }
    }

    for event in &result.events {
        if event.kind == JudgeEventKind::Slide
            && !displayed_slide_results.contains(&event.note_index)
        {
            if let Some(display) = make_judge_result_display(
                chart,
                engine,
                &result.events,
                event.note_index,
                event.kind,
                event.grade,
            ) {
                displayed_slide_results.insert(event.note_index);
                displays.push(display);
            }
        }
    }

    displays
}

fn make_judge_result_display(
    chart: &ChartDoc,
    engine: Option<&JudgeEngine>,
    events: &[JudgeEvent],
    note_index: u64,
    kind: JudgeEventKind,
    grade: JudgeGrade,
) -> Option<JudgeResultDisplay> {
    let zone = judge_result_zone(chart, engine, events, note_index, kind)?;
    let label = display_label_for_grade(grade);
    let duration = if grade.is_miss_or_too_fast() { 0.24 } else { 0.3 };
    let is_break = events
        .iter()
        .find(|e| e.note_index == note_index && e.kind == kind)
        .map(|e| e.is_break)
        .unwrap_or(false);
    Some(JudgeResultDisplay {
        zone,
        label,
        duration,
        kind,
        is_break,
        is_hit: !grade.is_miss_or_too_fast(),
    })
}

fn judge_result_zone(
    chart: &ChartDoc,
    engine: Option<&JudgeEngine>,
    events: &[JudgeEvent],
    note_index: u64,
    kind: JudgeEventKind,
) -> Option<PadZone> {
    if kind == JudgeEventKind::Slide {
        slide_tail_zone_for_runtime_note(chart, engine, note_index)
            .or_else(|| event_position_zone(events, note_index, kind))
    } else {
        event_position_zone(events, note_index, kind)
            .or_else(|| chart_note_head_zone(chart, note_index))
    }
}

fn display_label_for_grade(grade: JudgeGrade) -> &'static str {
    if grade.is_miss_or_too_fast() {
        "Miss"
    } else if grade.is_good_grade() {
        "Good"
    } else if grade.is_great_grade() {
        "Great"
    } else {
        "Perfect"
    }
}

fn judge_sfx_allowed(grade: JudgeGrade) -> bool {
    !grade.is_miss_or_too_fast()
}

fn event_position_zone(
    events: &[JudgeEvent],
    note_index: u64,
    kind: JudgeEventKind,
) -> Option<PadZone> {
    let ev = events
        .iter()
        .find(|ev| ev.note_index == note_index && ev.kind == kind)?;
    if let Some(button) = ev.position.button {
        Some(zone_for_button(button))
    } else {
        ev.position.sensor.map(zone_for_sensor)
    }
}

fn slide_tail_zone_for_runtime_note(
    chart: &ChartDoc,
    engine: Option<&JudgeEngine>,
    note_index: u64,
) -> Option<PadZone> {
    let runtime_slide_index = engine.and_then(|engine| engine.runtime_slide_index(note_index))?;
    chart_slide_tail_zone(chart, runtime_slide_index)
}

fn chart_slide_tail_zone(chart: &ChartDoc, runtime_slide_index: usize) -> Option<PadZone> {
    chart_slide_key(chart, runtime_slide_index).and_then(|(note_id, slide_idx)| {
        chart
            .notes
            .iter()
            .find(|note| note.id == note_id)
            .and_then(|note| note.slide.get(slide_idx))
            .and_then(|slide| slide.segments.last())
            .and_then(|segment| segment.points.last())
            .map(|point| point.zone)
    })
}

fn chart_note_head_zone(chart: &ChartDoc, note_index: u64) -> Option<PadZone> {
    chart_note(chart, note_index).map(|note| PadZone::from(note.lane))
}

/// Resolve the chart note for a lnmai `noteIndex` (the runtime index is the
/// chart note id, or a 1-based position when ids are absent).
fn chart_note<'a>(chart: &'a ChartDoc, note_index: u64) -> Option<&'a crate::app::types::Note> {
    chart
        .notes
        .iter()
        .find(|note| note.id == note_index)
        .or_else(|| {
            usize::try_from(note_index)
                .ok()
                .and_then(|index| chart.notes.get(index.saturating_sub(1)))
        })
}

/// Map a runtime slide index onto the chart's `(note_id, slide_idx)`.
///
/// lnmai-core splits a continuous multi-arc slide into one runtime slide per
/// arc, so each chart sub-slide consumes `slide.runtime_parts` runtime indices.
pub fn chart_slide_key(chart: &ChartDoc, runtime_slide_index: usize) -> Option<(u64, usize)> {
    chart_slide_position(chart, runtime_slide_index).map(|(note_id, slide_idx, _, _)| (note_id, slide_idx))
}

/// Like [`chart_slide_key`] but also resolves which **segment** (runtime arc)
/// of the chart sub-slide `runtime_slide_index` is, and how many segments the
/// sub-slide has: `(note_id, slide_idx, segment_idx, segment_count)`.
pub fn chart_slide_position(
    chart: &ChartDoc,
    runtime_slide_index: usize,
) -> Option<(u64, usize, usize, usize)> {
    let mut current = 0;
    chart
        .notes
        .iter()
        .filter(|note| matches!(note.note_type, NoteType::Slide))
        .find_map(|note| {
            for (slide_idx, slide) in note.slide.iter().enumerate() {
                let parts = slide.runtime_parts.max(1);
                if runtime_slide_index < current + parts {
                    return Some((note.id, slide_idx, runtime_slide_index - current, parts));
                }
                current += parts;
            }
            None
        })
}

fn play_audio_command(app: &mut PadPreviewState, command: &AudioCommand) {
    if !app.audio_enabled {
        return;
    }
    use crate::player::render::skin::SkinVariant;
    use crate::player::sfx::{self, SfxKind};

    // The per-kind hit SFX comes from actual hits (answer cue is timeline-driven
    // in `state::tick_cues`).
    let mut hit: Option<&crate::app::audio::SfxBuffer> = None;
    match command {
        AudioCommand::PlayJudgeSfx {
            kind,
            grade,
            is_break,
            note_index,
            ..
        } => {
            if judge_sfx_allowed(*grade) {
                let sfx_kind = match kind {
                    JudgeEventKind::Tap => SfxKind::Tap,
                    JudgeEventKind::Touch => SfxKind::Touch,
                    // lnmai reports touch-holds as `Hold`; they use the touch
                    // sound, regular holds the tap sound.
                    JudgeEventKind::Hold => {
                        if chart_note(&app.chart, *note_index).is_some_and(|n| n.is_touch) {
                            SfxKind::Touch
                        } else {
                            SfxKind::Tap
                        }
                    }
                    JudgeEventKind::Slide => SfxKind::SlideJudge,
                    JudgeEventKind::Break => SfxKind::Tap,
                };
                let is_break = *is_break || matches!(kind, JudgeEventKind::Break);
                hit = sfx::select(app, sfx_kind, SkinVariant::of_flags(is_break, false), false);
            }
        }
        AudioCommand::PlaySlideCue {
            is_break,
            ..
        } => {
            // The core explicitly requested the slide cue; do not synthesize
            // any local progress or deduplicate this command.
            hit = sfx::select(
                app,
                SfxKind::SlideCue,
                SkinVariant::of_flags(*is_break, false),
                false,
            );
        }
    }

    if crate::app::params::hit_sfx() {
        app.play_sfx(hit);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn bundled_maidata() -> String {
        std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/assets/charts/jack_ripper/maidata.txt"
        ))
        .expect("bundled maidata.txt")
    }

    #[test]
    fn engine_loads_and_steps_a_bundled_chart() {
        let text = bundled_maidata();
        let level = crate::app::maidata::inote_key(&text, None).expect("inote key");
        let mut engine = JudgeEngine::load(&text, level).expect("engine loads");

        let tactic = engine.default_tactic().expect("default tactic builds");
        assert!(!tactic.is_empty(), "replay tactic should contain events");

        engine.step(0.0, Vec::new()).expect("initial frame steps");
        engine
            .step(5.0, press_events_for_zone(PadZone::from(1), 5_000_000))
            .expect("press frame steps");
    }

    #[test]
    fn press_and_release_are_sensor_only() {
        let press = press_events_for_zone(PadZone::from(1), 123);
        assert_eq!(press.len(), 2);
        assert!(press.iter().all(|e| !matches!(
            e,
            TimedInputEvent::ButtonClick { .. } | TimedInputEvent::ButtonHold { .. }
        )));
        let release = release_events_for_zone(PadZone::from(1), 200);
        assert_eq!(release.len(), 1);
        assert!(matches!(
            release[0],
            TimedInputEvent::SensorHold { is_down: false, .. }
        ));
    }

    #[test]
    fn chart_slide_key_enumerates_slides_in_parse_order() {
        let text = bundled_maidata();
        let chart = crate::app::maidata::from_maidata(&text, None).expect("chart");
        let mut runtime = 0;
        for note in chart
            .notes
            .iter()
            .filter(|n| matches!(n.note_type, NoteType::Slide))
        {
            for si in 0..note.slide.len() {
                assert_eq!(chart_slide_key(&chart, runtime), Some((note.id, si)));
                runtime += 1;
            }
        }
        assert_eq!(chart_slide_key(&chart, runtime), None);
    }

    #[test]
    fn core_slide_hides_map_onto_the_chart() {
        let text = bundled_maidata();
        let chart = crate::app::maidata::from_maidata(&text, None).expect("chart");
        let chart_slides: usize = chart
            .notes
            .iter()
            .filter(|n| matches!(n.note_type, NoteType::Slide))
            .map(|n| n.slide.len())
            .sum();

        let level = crate::app::maidata::inote_key(&text, None).expect("level");
        let mut engine = JudgeEngine::load(&text, level).expect("engine");
        assert_eq!(
            engine.slide_count(),
            chart_slides,
            "runtime and chart slide counts must match for index mapping"
        );

        // Step through the chart with no input: slides miss and core hides them.
        let mut seen = std::collections::HashSet::new();
        let mut full = 0usize;
        let mut partial = 0usize;
        let mut t = 0.0_f32;
        while t < 180.0 {
            t += 0.2;
            let result = engine.step(t, Vec::new()).expect("step");
            for update in engine.slide_progress_updates(&result.render_commands) {
                assert!(
                    chart_slide_key(&chart, update.runtime_slide_index).is_some(),
                    "runtime slide {} must map to a chart slide",
                    update.runtime_slide_index
                );
                if update.frac >= 1.0 {
                    full += 1;
                } else {
                    partial += 1;
                }
                seen.insert(update.runtime_slide_index);
            }
        }
        eprintln!("no-input hide updates: full={full} partial={partial}");
        assert!(
            !seen.is_empty(),
            "missed slides should produce core hide commands"
        );
        assert_eq!(
            partial, 0,
            "with no input, core should only emit full (miss) hides, not partial"
        );
    }

    #[test]
    fn core_slide_order_matches_chart_order() {
        let text = bundled_maidata();
        let mut chart = crate::app::maidata::from_maidata(&text, None).expect("chart");
        crate::app::maichart::assign_note_ids(&mut chart.notes);
        let level = crate::app::maidata::inote_key(&text, None).expect("level");
        let engine = JudgeEngine::load(&text, level).expect("engine");

        let chart_heads: Vec<f32> = chart
            .notes
            .iter()
            .filter(|n| matches!(n.note_type, NoteType::Slide))
            .flat_map(|n| {
                let t = crate::app::types::note_secs(n, &chart.bpms);
                (0..n.slide.len()).map(move |_| t)
            })
            .collect();
        assert_eq!(chart_heads.len(), engine.slide_count());

        for (i, head_s) in chart_heads.iter().enumerate() {
            let core_s = engine.slide_head_timing(i).expect("timing") as f32 / 1e6;
            assert!(
                (core_s - head_s).abs() < 0.5,
                "runtime slide {i} head {core_s:.3}s != chart head {head_s:.3}s"
            );
        }
    }

    /// Continuous `>`/`<` chains stay **one** chart sub-slide (one star) but
    /// expand to one runtime slide per arc in lnmai-core; `chart_slide_key` must
    /// consume `runtime_parts` indices per sub-slide so the mapping stays aligned.
    #[test]
    fn multi_arc_chain_maps_runtime_to_grouped_sub_slides() {
        let text = "&title=T\n&inote_1=(120){4}1v4>3>2[4:1],4-8<4b[2:1]*-8>4b[2:1],5\n";
        let mut chart = crate::app::maidata::from_maidata(text, None).expect("chart");
        crate::app::maichart::assign_note_ids(&mut chart.notes);
        let level = crate::app::maidata::inote_key(text, None).expect("level");
        let engine = JudgeEngine::load(text, level).expect("engine");

        // Chart sub-slides: `1v4>3>2` = 1 (3 arcs), `4-8<4` and `-8>4` = 2 more.
        let chart_subs: usize = chart
            .notes
            .iter()
            .filter(|n| matches!(n.note_type, NoteType::Slide))
            .map(|n| n.slide.len())
            .sum();
        assert_eq!(chart_subs, 3);
        // Runtime slides: one per arc (3 + 2 + 2).
        assert_eq!(engine.slide_count(), 7);

        // Expand each chart sub-slide into its runtime indices.
        let mut expected: Vec<(u64, usize)> = Vec::new();
        for note in chart
            .notes
            .iter()
            .filter(|n| matches!(n.note_type, NoteType::Slide))
        {
            for (si, slide) in note.slide.iter().enumerate() {
                for _ in 0..slide.runtime_parts.max(1) {
                    expected.push((note.id, si));
                }
            }
        }
        assert_eq!(expected.len(), engine.slide_count());
        for (runtime, key) in expected.iter().enumerate() {
            assert_eq!(chart_slide_key(&chart, runtime), Some(*key));
        }
        // Runtime head timings match the owning sub-slide's head.
        for (runtime, (id, _)) in expected.iter().enumerate() {
            let note = chart.notes.iter().find(|n| n.id == *id).expect("note");
            let head_s = crate::app::types::note_secs(note, &chart.bpms);
            let core_s = engine.slide_head_timing(runtime).expect("timing") as f32 / 1e6;
            assert!(
                (core_s - head_s).abs() < 0.5,
                "runtime slide {runtime} head {core_s:.3}s != chart head {head_s:.3}s"
            );
        }
    }

    #[test]
    fn core_reports_combo_and_dx_score() {
        let text = bundled_maidata();
        let level = crate::app::maidata::inote_key(&text, None).expect("level");
        let mut engine = JudgeEngine::load(&text, level).expect("engine");
        let tactic = engine.default_tactic().expect("tactic");

        let mut cursor = 0usize;
        let mut max_combo = 0u64;
        let mut max_dx = 0u64;
        let mut total_dx = 0u64;
        let mut t = 0.0_f32;
        while t < 30.0 {
            t += 0.05;
            let now_us = (t * 1e6) as i64;
            let mut events = Vec::new();
            while cursor < tactic.len() && timed_input_tp(&tactic[cursor]) <= now_us {
                events.push(tactic[cursor].clone());
                cursor += 1;
            }
            let result = engine.step(t, events).expect("step");
            max_combo = max_combo.max(result.score.combo);
            max_dx = max_dx.max(result.score.dx_score_remaining() as u64);
            total_dx = result.score.max_dx_score;
        }
        assert!(max_combo > 0, "autoplay tactic should build a combo");
        assert!(total_dx > 0, "chart should have a DX score total");
        assert!(max_dx > 0, "autoplay should earn DX score");
    }

    /// Wifi's three tracks each report an explicit bar cutoff
    /// (`HideSlideTrackBars`), kept per track so they consume independently.
    #[test]
    fn wifi_track_hide_bars_are_per_track() {
        let text = "&title=D\n&inote_1=(120){4}1w5[4:1],E\n";
        let mut engine = JudgeEngine::load(text, 1).expect("engine");
        let tactic = engine.default_tactic().expect("tactic");
        let mut cursor = 0usize;
        let mut tracks: std::collections::BTreeSet<Option<u64>> = Default::default();
        let mut max_bar = 0usize;
        let mut t = 0.0_f32;
        while t < 6.0 {
            t += 0.02;
            let now_us = (t * 1e6) as i64;
            let mut events = Vec::new();
            while cursor < tactic.len() && timed_input_tp(&tactic[cursor]) <= now_us {
                events.push(tactic[cursor].clone());
                cursor += 1;
            }
            let result = engine.step(t, events).expect("step");
            for u in engine.slide_progress_updates(&result.render_commands) {
                if let Some(bar) = u.hidden_until_bar {
                    tracks.insert(u.track_index);
                    max_bar = max_bar.max(bar);
                }
            }
        }
        assert_eq!(tracks.len(), 3, "all three wifi tracks report a bar cutoff");
        assert!(max_bar > 0);
    }

    /// A frame can bundle several arc transitions of a very fast slide (a long
    /// `^` chain), which needs a per-arc clock; a following ordinary slide must
    /// still be judged with the batched frame clock. Both must complete.
    #[test]
    fn sparse_and_dense_slides_both_complete() {
        let text = "&title=T\n&inote_1=(210){4},,,7^2^3^2^3^2^3^2^3^2^3^2^3^2^3^2^3^2^3^2>6[4:1],,,,6-2>5-1[4:3]/8\n";
        let mut engine = JudgeEngine::load(text, 1).expect("engine");
        let tactic = engine.default_tactic().expect("tactic");
        let mut cursor = 0usize;
        let mut t = 0.0_f32;
        let mut grades = Vec::new();
        while t < 8.0 {
            t += 1.0 / 60.0;
            let now = (t * 1e6) as i64;
            let mut events = Vec::new();
            while cursor < tactic.len() && timed_input_tp(&tactic[cursor]) <= now {
                events.push(tactic[cursor].clone());
                cursor += 1;
            }
            for r in step_engine_events(&mut engine, t, events) {
                for e in r.unwrap().events {
                    if e.kind == JudgeEventKind::Slide {
                        grades.push((e.note_index, e.grade));
                    }
                }
            }
        }
        assert!(!grades.is_empty(), "slides should be judged");
        assert!(
            !grades.iter().any(|(_, g)| *g == JudgeGrade::Miss),
            "neither the fast chain nor the normal slide may miss: {grades:?}"
        );
    }
}
