//! Judgment engine bridge to `lnmai-core`'s Lean FFI runtime.
//!
//! The chart is loaded into a persistent Lean runtime session; each gameplay
//! frame the player feeds a [`TimedInputBatch`] (button/sensor presses at the
//! current song time in µs) and reads back the resulting judge events. The
//! player no longer computes judge windows itself.

use lambda_dx::app::types::zone::PadZone;
use lnmai_core::session::{self, Empty, Loaded, Session};
use lnmai_core::types::{
    ButtonZone, JudgeEvent, JudgeEventKind, SensorArea, TimedInputBatch, TimedInputEvent,
};
use std::time::Instant;

/// Map a pad zone to its native lnmai input family.
///
/// A-ring zones return button events here. The player aliases those zones to
/// matching sensor events through [`press_events_for_zone`] and
/// [`release_events_for_zone`] because outer-ring contact also drives slides
/// and touch notes.
/// Returns `(click_event, hold_down, hold_up)` for one press/release cycle.
pub fn events_for_zone(
    zone: PadZone,
    tp: i64,
) -> Option<(TimedInputEvent, TimedInputEvent, TimedInputEvent)> {
    let zid = zone.to_id();
    let (click, hold_down, hold_up) = if zid <= 8 {
        let btn = match zid {
            1 => ButtonZone::K1,
            2 => ButtonZone::K2,
            3 => ButtonZone::K3,
            4 => ButtonZone::K4,
            5 => ButtonZone::K5,
            6 => ButtonZone::K6,
            7 => ButtonZone::K7,
            8 => ButtonZone::K8,
            _ => return None,
        };
        (
            TimedInputEvent::ButtonClick { tp, zone: btn },
            TimedInputEvent::ButtonHold {
                tp,
                zone: btn,
                is_down: true,
            },
            TimedInputEvent::ButtonHold {
                tp,
                zone: btn,
                is_down: false,
            },
        )
    } else {
        sensor_events_for_zone(zone, tp)?
    };
    Some((click, hold_down, hold_up))
}

/// Map any pad zone to its corresponding lnmai sensor area.
///
/// The core keeps outer-button notes and sensor notes separate. The player
/// deliberately aliases A-ring input to the matching sensor area as well, so
/// slide bodies can be driven from the same physical/manual contact.
pub fn sensor_events_for_zone(
    zone: PadZone,
    tp: i64,
) -> Option<(TimedInputEvent, TimedInputEvent, TimedInputEvent)> {
    let area = match zone.to_id() {
        1 => SensorArea::A1,
        2 => SensorArea::A2,
        3 => SensorArea::A3,
        4 => SensorArea::A4,
        5 => SensorArea::A5,
        6 => SensorArea::A6,
        7 => SensorArea::A7,
        8 => SensorArea::A8,
        9 => SensorArea::B1,
        10 => SensorArea::B2,
        11 => SensorArea::B3,
        12 => SensorArea::B4,
        13 => SensorArea::B5,
        14 => SensorArea::B6,
        15 => SensorArea::B7,
        16 => SensorArea::B8,
        17 => SensorArea::C,
        18 => SensorArea::D1,
        19 => SensorArea::D2,
        20 => SensorArea::D3,
        21 => SensorArea::D4,
        22 => SensorArea::D5,
        23 => SensorArea::D6,
        24 => SensorArea::D7,
        25 => SensorArea::D8,
        26 => SensorArea::E1,
        27 => SensorArea::E2,
        28 => SensorArea::E3,
        29 => SensorArea::E4,
        30 => SensorArea::E5,
        31 => SensorArea::E6,
        32 => SensorArea::E7,
        33 => SensorArea::E8,
        _ => return None,
    };
    Some((
        TimedInputEvent::SensorClick { tp, area },
        TimedInputEvent::SensorHold {
            tp,
            area,
            is_down: true,
        },
        TimedInputEvent::SensorHold {
            tp,
            area,
            is_down: false,
        },
    ))
}

fn press_events_from(
    events: Option<(TimedInputEvent, TimedInputEvent, TimedInputEvent)>,
) -> Vec<TimedInputEvent> {
    let mut result = Vec::with_capacity(2);
    if let Some((click, hold_down, _)) = events {
        result.push(click);
        result.push(hold_down);
    }
    result
}

fn release_events_from(
    events: Option<(TimedInputEvent, TimedInputEvent, TimedInputEvent)>,
) -> Vec<TimedInputEvent> {
    events
        .map(|(_, _, hold_up)| vec![hold_up])
        .unwrap_or_default()
}

/// Build the native lnmai press for one chart zone.
///
/// This keeps autoplay aligned with the chart's note family: A-ring chart
/// notes use button events, while all other chart zones use sensor events.
fn native_press_events_for_zone(zone: PadZone, tp: i64) -> Vec<TimedInputEvent> {
    press_events_from(events_for_zone(zone, tp))
}

/// Build the sensor press used by slide-body autoplay.
fn sensor_press_events_for_zone(zone: PadZone, tp: i64) -> Vec<TimedInputEvent> {
    press_events_from(sensor_events_for_zone(zone, tp))
}

/// Build the complete logical press generated by one active pad zone.
pub fn press_events_for_zone(zone: PadZone, tp: i64) -> Vec<TimedInputEvent> {
    let mut events = native_press_events_for_zone(zone, tp);
    if zone.to_id() <= 8 {
        events.extend(sensor_press_events_for_zone(zone, tp));
    }
    events
}

/// Build the complete logical release generated by one active pad zone.
pub fn release_events_for_zone(zone: PadZone, tp: i64) -> Vec<TimedInputEvent> {
    let mut events = release_events_from(events_for_zone(zone, tp));
    if zone.to_id() <= 8 {
        events.extend(release_events_from(sensor_events_for_zone(zone, tp)));
    }
    events
}

/// Convert a button zone back to a [`PadZone`] (for engine judge feedback).
pub fn zone_for_button(btn: ButtonZone) -> PadZone {
    let id = match btn {
        ButtonZone::K1 => 1,
        ButtonZone::K2 => 2,
        ButtonZone::K3 => 3,
        ButtonZone::K4 => 4,
        ButtonZone::K5 => 5,
        ButtonZone::K6 => 6,
        ButtonZone::K7 => 7,
        ButtonZone::K8 => 8,
    };
    PadZone::from(id)
}

/// Convert a sensor area to a pad zone id (1-8 A, 9-16 B, 17 C, 18-25 D, 26-33 E).
pub fn zone_for_sensor(area: SensorArea) -> PadZone {
    let id = match area {
        SensorArea::A1 => 1,
        SensorArea::A2 => 2,
        SensorArea::A3 => 3,
        SensorArea::A4 => 4,
        SensorArea::A5 => 5,
        SensorArea::A6 => 6,
        SensorArea::A7 => 7,
        SensorArea::A8 => 8,
        SensorArea::B1 => 9,
        SensorArea::B2 => 10,
        SensorArea::B3 => 11,
        SensorArea::B4 => 12,
        SensorArea::B5 => 13,
        SensorArea::B6 => 14,
        SensorArea::B7 => 15,
        SensorArea::B8 => 16,
        SensorArea::C => 17,
        SensorArea::D1 => 18,
        SensorArea::D2 => 19,
        SensorArea::D3 => 20,
        SensorArea::D4 => 21,
        SensorArea::D5 => 22,
        SensorArea::D6 => 23,
        SensorArea::D7 => 24,
        SensorArea::D8 => 25,
        SensorArea::E1 => 26,
        SensorArea::E2 => 27,
        SensorArea::E3 => 28,
        SensorArea::E4 => 29,
        SensorArea::E5 => 30,
        SensorArea::E6 => 31,
        SensorArea::E7 => 32,
        SensorArea::E8 => 33,
    };
    PadZone::from(id)
}

/// A loaded lnmai-core (FFI) runtime session.
pub struct JudgeEngine {
    session: Session<Loaded>,
}

fn ensure_runtime() {
    session::ensure_runtime().expect("lnmai-core runtime must initialize");
}

impl JudgeEngine {
    /// Create a session and load the chart at `level_index` from Simai text.
    pub fn load(simai_text: &str, level_index: u32) -> Result<Self, String> {
        ensure_runtime();
        let empty = Session::<Empty>::create().map_err(|e| e.json)?;
        let (loaded, _envelope) = empty
            .load_chart_text(simai_text, level_index)
            .map_err(|e| e.json)?;
        Ok(JudgeEngine { session: loaded })
    }

    /// Advance the runtime by one frame with the given input events at
    /// `current_secs` (song time in seconds, converted to µs ticks). Returns
    /// the judge events produced this frame.
    pub fn step(
        &mut self,
        current_secs: f32,
        mut events: Vec<TimedInputEvent>,
    ) -> Result<Vec<JudgeEvent>, String> {
        events.sort_by_key(|e| e.tp());
        let batch = TimedInputBatch {
            current_time: (current_secs.max(0.0) * 1e6) as i64,
            events,
        };
        let t_ser = Instant::now();
        let json = serde_json::to_string(&batch).map_err(|e| e.to_string())?;
        let ser_ns = t_ser.elapsed();

        let (envelope, ffi_timings) = self
            .session
            .advance_frame_light_timed(&json)
            .map_err(|e| e.json)?;

        let t_de = Instant::now();
        let value: serde_json::Value =
            serde_json::from_str(&envelope.json).map_err(|e| e.to_string())?;
        let events_json = value
            .get("result")
            .and_then(|r| r.get("events"))
            .cloned()
            .unwrap_or_default();
        let events = serde_json::from_value(events_json).map_err(|e| e.to_string())?;
        let de_ns = t_de.elapsed();

        crate::perf::record("engine.serialize", ser_ns);
        crate::perf::record(
            "engine.ffi.mk_string",
            std::time::Duration::from_nanos(ffi_timings.mk_string_ns),
        );
        crate::perf::record(
            "engine.ffi.lean",
            std::time::Duration::from_nanos(ffi_timings.ffi_ns),
        );
        crate::perf::record(
            "engine.ffi.into_string",
            std::time::Duration::from_nanos(ffi_timings.into_string_ns),
        );
        crate::perf::record("engine.deserialize", de_ns);

        Ok(events)
    }
}

trait InputTp {
    fn tp(&self) -> i64;
}
impl InputTp for TimedInputEvent {
    fn tp(&self) -> i64 {
        match self {
            TimedInputEvent::ButtonClick { tp, .. }
            | TimedInputEvent::ButtonHold { tp, .. }
            | TimedInputEvent::SensorClick { tp, .. }
            | TimedInputEvent::SensorHold { tp, .. } => *tp,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{
        native_press_events_for_zone, press_events_for_zone, sensor_press_events_for_zone,
        JudgeEngine,
    };
    use lambda_dx::simai_io::{parse_simai_source, simai_file_to_chart_doc};
    use lambda_dx::types::zone::PadZone;
    use lambda_dx::types::{
        BpmChange, ChartDoc, Note, NoteType, Slide, SlidePoint, SlideSegment, SlideShape,
    };
    use lnmai_core::types::{SensorArea, TimedInputEvent};
    use serde_json::Value;

    fn sample_outer_ring_slide_chart() -> String {
        let chart = ChartDoc {
            version: "1.0".to_string(),
            title: "outer-ring-slide-probe".to_string(),
            artist: String::new(),
            simai_level: 6,
            bpm: 120.0,
            bpms: vec![BpmChange {
                measure: 1.0,
                bpm: 120.0,
            }],
            audio_offset: 0.0,
            notes: vec![Note {
                time: 1.0,
                lane: 1,
                note_type: NoteType::Slide,
                is_star: true,
                slide: vec![Slide {
                    segments: vec![SlideSegment {
                        points: vec![SlidePoint::from(PadZone::from(5_u8))],
                        shape: SlideShape::Line,
                    }],
                    slide_duration: 1.0,
                    slide_start_delay: 0.25,
                    slide_is_break: false,
                }],
                ..Default::default()
            }],
            templates: vec![],
            template_instances: vec![],
        };
        let file = lambda_dx::simai_io::chart_doc_to_simai_file(&chart);
        lambda_dx::simai_io::export_simai_file(&file)
    }

    fn session_state(engine: &JudgeEngine) -> Value {
        let envelope = engine
            .session
            .get_state_json()
            .expect("player engine should expose its current state");
        serde_json::from_str(&envelope.json).expect("player engine state should be valid JSON")
    }

    #[test]
    fn importing_then_loading_the_player_engine_does_not_abort() {
        let source = include_str!("../../songs/Imported Simai/maidata.txt");
        let file = parse_simai_source(source).expect("fixture must parse");
        let chart = simai_file_to_chart_doc(&file, None).expect("fixture must convert");

        let engine = JudgeEngine::load(file.source_text(), chart.simai_level)
            .expect("player engine must load the imported chart");
        drop(engine);
    }

    #[test]
    fn outer_ring_press_also_drives_the_matching_sensor_for_slide_bodies() {
        let events = press_events_for_zone(PadZone::from(1), 123);

        assert_eq!(events.len(), 4);
        assert!(events.iter().any(|event| {
            matches!(
                event,
                TimedInputEvent::SensorClick {
                    area: SensorArea::A1,
                    ..
                }
            )
        }));
        assert!(events.iter().any(|event| {
            matches!(
                event,
                TimedInputEvent::SensorHold {
                    area: SensorArea::A1,
                    is_down: true,
                    ..
                }
            )
        }));
    }

    #[test]
    fn native_outer_ring_press_stays_button_only() {
        let events = native_press_events_for_zone(PadZone::from(1), 123);

        assert_eq!(events.len(), 2);
        assert!(events.iter().all(|event| matches!(
            event,
            TimedInputEvent::ButtonClick { .. } | TimedInputEvent::ButtonHold { .. }
        )));
    }

    #[test]
    fn sensor_press_can_target_an_outer_ring_slide_body() {
        let events = sensor_press_events_for_zone(PadZone::from(1), 123);

        assert_eq!(events.len(), 2);
        assert!(events.iter().all(|event| {
            matches!(
                event,
                TimedInputEvent::SensorClick {
                    area: SensorArea::A1,
                    ..
                } | TimedInputEvent::SensorHold {
                    area: SensorArea::A1,
                    ..
                }
            )
        }));
    }

    #[test]
    fn outer_ring_release_also_releases_the_matching_sensor() {
        let events = super::release_events_for_zone(PadZone::from(1), 123);

        assert!(events.iter().any(|event| {
            matches!(
                event,
                TimedInputEvent::SensorHold {
                    area: SensorArea::A1,
                    is_down: false,
                    ..
                }
            )
        }));
    }

    #[test]
    fn non_outer_sensor_press_is_not_duplicated() {
        assert_eq!(press_events_for_zone(PadZone::from(9), 123).len(), 2);
    }

    #[test]
    fn outer_ring_input_advances_the_core_slide_sensor_queue() {
        let mut engine =
            JudgeEngine::load(&sample_outer_ring_slide_chart(), 6).expect("slide chart loads");

        engine
            .step(0.0, Vec::new())
            .expect("initial core frame should succeed");
        engine
            .step(0.8, press_events_for_zone(PadZone::from(1), 800_000))
            .expect("A-ring press should reach the core");

        let state = session_state(&engine);
        let first_area = &state["result"]["slides"][0]["judgeQueues"][0][0];
        assert_eq!(first_area["targetAreas"][0], "A1");
        assert_eq!(
            first_area["wasOn"], true,
            "the player-style A-ring press must be visible as held sensor input"
        );
    }
}

use lambda_dx::app::types::note_secs;
use lambda_dx::app::types::sanitize_note_zone;
use lambda_dx::app::types::{mdur_to_secs, NoteType};

fn tp_at(secs: f32) -> i64 {
    (secs.max(0.0) * 1e6) as i64
}

/// Feed autoplay clicks for notes whose judge time has passed, then advance the
/// engine and apply the resulting judge events to the player's feedback.
pub fn step_judge_engine(app: &mut crate::state::PlayerState) {
    if app.judge_engine.is_none() {
        return;
    }
    let t0 = Instant::now();

    if app.autoplay {
        let now = app.song_time();
        let bpms = app.chart.bpms.clone();
        for note in &app.chart.notes {
            let ns = note_secs(note, &bpms);
            match note.note_type {
                NoteType::Slide => {
                    // Feed sensor clicks along each slide's waypoint zones so
                    // the engine can judge slides in autoplay.
                    for sl in &note.slide {
                        let start = ns + mdur_to_secs(sl.slide_start_delay, note.time, &bpms);
                        let dur = mdur_to_secs(sl.slide_duration, note.time, &bpms).max(0.05);
                        let mut zones = vec![note.lane];
                        for seg in &sl.segments {
                            for p in &seg.points {
                                let zid = p.zone.to_id();
                                if zones.last() != Some(&zid) {
                                    zones.push(zid);
                                }
                            }
                        }
                        for (k, zid) in zones.iter().enumerate() {
                            if !app.auto_slide_sensors.contains(&(note.id, *zid)) {
                                let frac = if zones.len() <= 1 {
                                    0.0
                                } else {
                                    k as f32 / (zones.len() - 1) as f32
                                };
                                let t = start + dur * frac;
                                if t <= now + 0.02 {
                                    app.engine_events.extend(sensor_press_events_for_zone(
                                        PadZone::from(*zid),
                                        tp_at(t),
                                    ));
                                    app.auto_slide_sensors.insert((note.id, *zid));
                                }
                            }
                        }
                    }
                }
                _ => {
                    if app.auto_judged.contains(&note.id) {
                        continue;
                    }
                    if ns <= now + 0.02 {
                        let zone = PadZone::from(sanitize_note_zone(note.note_type, note.lane));
                        app.engine_events
                            .extend(native_press_events_for_zone(zone, tp_at(ns)));
                        app.auto_judged.insert(note.id);
                    }
                }
            }
        }
    }

    let now = app.song_time();
    let events = std::mem::take(&mut app.engine_events);
    let result = app.judge_engine.as_mut().unwrap().step(now, events);
    match result {
        Ok(events) => handle_engine_events(app, events),
        Err(e) => {
            if !app.status.starts_with("判引擎") {
                app.set_status(format!("engine: {e}"));
            }
        }
    }
    crate::perf::record("engine.total", t0.elapsed());
}

fn handle_engine_events(app: &mut crate::state::PlayerState, events: Vec<JudgeEvent>) {
    let now = app.song_time();
    let bpms = app.chart.bpms.clone();
    for ev in events {
        let is_slide = ev.kind == JudgeEventKind::Slide;
        let pos_zone = || {
            if let Some(b) = ev.position.button {
                Some(zone_for_button(b))
            } else if let Some(s) = ev.position.sensor {
                Some(zone_for_sensor(s))
            } else {
                None
            }
        };
        // The engine reports the slide's head button; show slide feedback at
        // the slide's tail zone with the slide color instead.
        let zone = if is_slide {
            find_slide_tail_zone(app, now, &bpms).or_else(pos_zone)
        } else {
            pos_zone()
        };
        let Some(zone) = zone else {
            continue;
        };
        // Raw lnmai grade string (e.g. "Perfect", "LatePerfect2nd", "Miss"),
        // matching the 8464c6f judge display.
        let label = format!("{:?}", ev.grade);
        let is_miss = ev.grade.is_miss_or_too_fast();
        let duration = if is_miss { 0.24 } else { 0.3 };
        app.push_judgement_colored(
            zone,
            &label,
            duration,
            macroquad::prelude::Color::from_rgba(255, 255, 255, 255),
        );

        if !is_miss {
            let sfx = match ev.kind {
                JudgeEventKind::Break => app.sfx_break_tap.as_ref(),
                JudgeEventKind::Touch => app.sfx_touch.as_ref(),
                JudgeEventKind::Slide => app.sfx_slide.as_ref(),
                _ => app.sfx_tap.as_ref(),
            };
            if let (Some(s), Some(player)) = (sfx, &mut app.sfx_player) {
                player.play(s, 1.0);
            }
        }
    }
}

/// Find the tail zone of the slide note currently in its run window (used to
/// place slide judge feedback).
fn find_slide_tail_zone(
    app: &crate::state::PlayerState,
    now: f32,
    bpms: &[lambda_dx::app::types::BpmChange],
) -> Option<PadZone> {
    use lambda_dx::app::types::{slide_end_time, NoteType};
    app.chart
        .notes
        .iter()
        .filter(|n| matches!(n.note_type, NoteType::Slide))
        .filter(|n| {
            let start = note_secs(n, bpms);
            let end = slide_end_time(n, bpms);
            // Judge events fire near the slide end; allow a small grace window.
            now >= start - 0.1 && now <= end + 1.0
        })
        .min_by(|a, b| {
            let da = (slide_end_time(a, bpms) - now).abs();
            let db = (slide_end_time(b, bpms) - now).abs();
            da.partial_cmp(&db).unwrap_or(std::cmp::Ordering::Equal)
        })
        .and_then(|n| {
            n.slide
                .last()
                .and_then(|sl| sl.segments.last())
                .and_then(|seg| seg.points.last())
                .map(|p| p.zone)
        })
}
