[package]
name = "macroanimate"
version = "0.2.1"
edition = "2024"
description = "Adobe Animate sparrow and texture atlas parser and renderer for Macroquad."
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/FunkinRustUp/macroanimate/"

[dependencies]
macroquad = "0.4.15"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
roxmltree = "0.20"
zip = { version = "2", default-features = false, features = ["deflate"] }
flate2 = "1"
